# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemographicSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="singleton",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="कुल जनसंख्या"
                    ),
                ),
                (
                    "population_male",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="पुरुष जनसंख्या"
                    ),
                ),
                (
                    "population_female",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="महिला जनसंख्या"
                    ),
                ),
                (
                    "population_other",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="अन्य जनसंख्या"
                    ),
                ),
                (
                    "population_absentee_total",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="कुल अनुपस्थित जनसंख्या"
                    ),
                ),
                (
                    "population_male_absentee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="अनुपस्थित पुरुष जनसंख्या"
                    ),
                ),
                (
                    "population_female_absentee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="अनुपस्थित महिला जनसंख्या"
                    ),
                ),
                (
                    "population_other_absentee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="अनुपस्थित अन्य जनसंख्या"
                    ),
                ),
                (
                    "sex_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="लिङ्ग अनुपात",
                    ),
                ),
                (
                    "total_households",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="कुल घरपरिवार"
                    ),
                ),
                (
                    "average_household_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="औसत घरपरिवार आकार",
                    ),
                ),
                (
                    "population_density",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="जनसंख्या घनत्व",
                    ),
                ),
                (
                    "population_0_to_14",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="०-१४ वर्ष जनसंख्या"
                    ),
                ),
                (
                    "population_15_to_59",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="१५-५९ वर्ष जनसंख्या"
                    ),
                ),
                (
                    "population_60_and_above",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="६० वर्षभन्दा माथि जनसंख्या"
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="वृद्धि दर",
                    ),
                ),
                (
                    "literacy_rate_above_15",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="१५ वर्षभन्दा माथि साक्षरता दर",
                    ),
                ),
                (
                    "literacy_rate_15_to_24",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="१५-२४ वर्ष साक्षरता दर",
                    ),
                ),
            ],
            options={
                "verbose_name": "जनसांख्यिकीय सारांश",
                "verbose_name_plural": "जनसांख्यिकीय सारांश",
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideCastePopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caste",
                    models.CharField(
                        choices=[
                            ("CHHETRI", "क्षेत्री"),
                            ("BRAHMIN_HILL", "ब्राह्मण पहाड"),
                            ("LIMBU", "लिम्बु"),
                            ("SHERPA", "शेर्पा"),
                            ("TAMANG", "तामाङ"),
                            ("RAI", "राई"),
                            ("MAGAR", "मगर"),
                            ("THARU", "थारु"),
                            ("NEWAR", "नेवार"),
                            ("KAMI", "कामी"),
                            ("MUSALMAN", "मुसलमान"),
                            ("YADAV", "यादव"),
                            ("GURUNG", "गुरुङ"),
                            ("DAMAI", "दमाई/ढोली"),
                            ("THAKURI", "ठकुरी"),
                            ("SARKI", "सार्की"),
                            ("TELI", "तेली"),
                            ("CHAMAR", "चमार/हरिजन/राम"),
                            ("KOIRI", "कोइरी/कुशवाहा"),
                            ("MUSHAR", "मुसहर"),
                            ("KURMI", "कुर्मी"),
                            ("SANYASI", "सन्यासी/दशनामी"),
                            ("DHANUK", "धानुक"),
                            ("DUSADH", "दुसाध/पाशवान/पासी"),
                            ("MALLAHA", "मल्लाह"),
                            ("KEWAT", "केवट"),
                            ("KATHBANIYA", "कथबनियाँ"),
                            ("BRAHMIN_TERAI", "ब्राह्मण तराई"),
                            ("KALWAR", "कलवार"),
                            ("KANU", "कानु"),
                            ("KUMAL", "कुमाल"),
                            ("GHARTI", "घर्ती/भुजेल"),
                            ("HAJAM", "हजाम/ठाकुर"),
                            ("RAJBANSHI", "राजवंशी"),
                            ("DHOBI", "धोबी"),
                            ("TATMA", "तत्मा/तत्वा"),
                            ("LOHAR", "लोहार"),
                            ("KHATWE", "खत्वे"),
                            ("SUNDI", "सुँडी"),
                            ("DANUWAR", "दनुवार"),
                            ("HALUWAI", "हलुवाई"),
                            ("MAJHI", "माझी"),
                            ("BARAI", "बरई"),
                            ("BIN", "बिन"),
                            ("NUNIA", "नुनिया"),
                            ("CHEPANG", "चेपाङ/प्रजा"),
                            ("SONAR", "सोनार"),
                            ("KUMHAR", "कुम्हार"),
                            ("SUNUWAR", "सुनुवार"),
                            ("BANTAR", "बाँतर/सरदार"),
                            ("KAHAR", "काहर/कोहार"),
                            ("SATAR", "सतार/सन्थाल"),
                            ("MARWADI", "मारवाडी"),
                            ("KAYASTHA", "कायस्थ"),
                            ("RAJPUT", "राजपुत"),
                            ("BADI", "बादी"),
                            ("JHANGAD", "झाँगड/धागर"),
                            ("GANGAI", "गनगाई"),
                            ("LODH", "लोध"),
                            ("BADHAI", "बढई"),
                            ("THAMI", "थामी"),
                            ("KULUNG", "कुलुङ"),
                            ("BENGALI", "बंगाली"),
                            ("GADERI", "गडेरी/भेडियार"),
                            ("DHIMAL", "धिमाल"),
                            ("YAKHHA", "याक्खा"),
                            ("GHALE", "घले"),
                            ("TAJPURIYA", "ताजपुरिया"),
                            ("KHAWAS", "खवास"),
                            ("DARAI", "दराई"),
                            ("MAALI", "माली"),
                            ("DHUNIYA", "धुनिया"),
                            ("PAHARI", "पहारी"),
                            ("RAAJDHOB", "राजधोव"),
                            ("BHOTE", "भोटे"),
                            ("DOM", "डोम"),
                            ("THAKALI", "थकाली"),
                            ("KORI", "कोरी"),
                            ("CHATYAL", "छन्त्याल/छन्तेल"),
                            ("HYOLMO", "ह्योल्मो"),
                            ("BOTE", "बोटे"),
                            ("RAJBHAR", "राजभर"),
                            ("BARAM", "बराम/बरामु/बरामो"),
                            ("PUNJABI", "पञ्जाबी/सिख"),
                            ("NACHIRING", "नाछिरिङ"),
                            ("YAMPHU", "याम्फु"),
                            ("GAINE", "गाइने"),
                            ("CHAMLING", "चाम्लिङ"),
                            ("AATHPAHARIYA", "आठपहरिया"),
                            ("JIREL", "जिरेल"),
                            ("DURA", "दुरा"),
                            ("SARBARIYA", "सरबरिया"),
                            ("MECHE", "मेचे"),
                            ("BANTAWA", "बान्तवा"),
                            ("RAJI", "राजी"),
                            ("DOLPO", "डोल्पो"),
                            ("HALAKHOR", "हलखोर"),
                            ("BYASI", "ब्यासी/सौका"),
                            ("AMAT", "अमात"),
                            ("THULUNG", "थुलुङ"),
                            ("LEPCHA", "लेप्चा"),
                            ("PATTHARKATTA", "पत्थरकट्टा/कुशवाडिया"),
                            ("MEWAHANG", "मेवाहाङ"),
                            ("BAHING", "बाहिङ"),
                            ("NATUWA", "नटुवा"),
                            ("HAYU", "हायु"),
                            ("DHANKAR", "धनकार/धरिकार"),
                            ("LHOPA", "ल्होपा"),
                            ("MUNDA", "मुण्डा"),
                            ("DEV", "देव"),
                            ("DHANDI", "ढाँडी"),
                            ("KAMAR", "कमर"),
                            ("KISAN", "किसान"),
                            ("SAMPANG", "साम्पाङ"),
                            ("KOCHE", "कोचे"),
                            ("LHOMI", "ह्लोमी"),
                            ("KHALING", "खालिङ"),
                            ("TOPKEGOLA", "तोप्केगोला"),
                            ("CHIDIMAR", "चिडिमार"),
                            ("WALUNG", "वालुङ"),
                            ("LOHARUNG", "लोहारूङ"),
                            ("KALAR", "कलार"),
                            ("RAUTE", "राउटे"),
                            ("NURANG", "नुराङ"),
                            ("KUSUNDA", "कुशुण्डा"),
                            ("RANATHARU", "रानाथारू"),
                            ("BHUMIHAR", "भूमिहार"),
                            ("FOREIGN", "विदेशी"),
                            ("OTHER", "अन्य ..."),
                        ],
                        max_length=50,
                        verbose_name="जात",
                    ),
                ),
                ("population", models.PositiveIntegerField(verbose_name="जनसंख्या")),
            ],
            options={
                "verbose_name": "जात विवरण",
                "verbose_name_plural": "जात विवरण",
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideMotherTonguePopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("NEPALI", "नेपाली"),
                            ("LIMBU", "लिम्बु"),
                            ("RAI", "राई"),
                            ("HINDI", "हिन्दी"),
                            ("NEWARI", "नेवारी"),
                            ("SHERPA", "शेर्पा"),
                            ("TAMANG", "तामाङ"),
                            ("MAITHILI", "मैथिली"),
                            ("BHOJPURI", "भोजपुरी"),
                            ("THARU", "थारू"),
                            ("BAJJIKA", "बज्जिका"),
                            ("MAGAR", "मगर"),
                            ("DOTELI", "डोटेली"),
                            ("URDU", "उर्दू"),
                            ("AWADI", "अवधी"),
                            ("GURUNG", "गुरूङ"),
                            ("BAITADELI", "बैतडेली"),
                            ("AACHAMI", "अछामी"),
                            ("BANTAWA", "बान्तवा"),
                            ("RAJBANSHI", "राजवंशी"),
                            ("CHAMLING", "चाम्लिङ"),
                            ("BAJHANGI", "बझाङ्गी"),
                            ("SANTHALI", "सन्थाली"),
                            ("CHEPANG", "चेपाङ"),
                            ("DANUWAR", "दनुवार"),
                            ("SUNUWAR", "सुनुवार"),
                            ("MAGAHI", "मगही"),
                            ("URAUN", "उराउँ/उराउ"),
                            ("KULUNG", "कुलुङ"),
                            ("KHAM", "खाम"),
                            ("RAJASTHANI", "राजस्थानी"),
                            ("MAJHI", "माझी"),
                            ("THAMI", "थामी"),
                            ("BHUJEL", "भुजेल"),
                            ("BANGALA", "बङला"),
                            ("THULUNG", "थुलुङ"),
                            ("YAKKHA", "यक्खा"),
                            ("DHIMAL", "धिमाल"),
                            ("TAJPURIYA", "ताजपुरिया"),
                            ("ANGIKA", "अंगिका"),
                            ("SAMPANG", "सामपाङ"),
                            ("KHALING", "खालिङ"),
                            ("YAMBULE", "याम्बुले"),
                            ("KUMAL", "कुमाल"),
                            ("DARAI", "दरई"),
                            ("BAHING", "बाहिङ"),
                            ("BAJURELI", "बाजुरेली"),
                            ("HYOLMO", "ह्योल्मो/योल्मो"),
                            ("NACHIRING", "नाछिरिङ्ग"),
                            ("YAMPHU", "याम्फू/याम्फे"),
                            ("BOTE", "बोटे"),
                            ("GHARE", "घले"),
                            ("DUMI", "डुमी"),
                            ("LAPCHA", "लाप्चा"),
                            ("PUMA", "पुमा"),
                            ("DUMANGLI", "डुङ्माली"),
                            ("DARCHULELI", "दार्चुलेली"),
                            ("AATHPAHARIYA", "आठपहरिया"),
                            ("THAKALI", "थकाली"),
                            ("JIREL", "जिरेल"),
                            ("MEWAHANG", "मेवाहाङ"),
                            ("SYMBOLIC_LANGUAGE", "सांकेतिक भाषा"),
                            ("TIBETIAN", "तिबेतियन"),
                            ("MECHE", "मेचे"),
                            ("CHANTYAL", "छन्त्याल"),
                            ("RAJI", "राजी"),
                            ("LOHARUNG", "लोहरूङ"),
                            ("CHINTANG", "छिन्ताङ"),
                            ("GANGAI", "गनगाई"),
                            ("PAHARI", "पहरी"),
                            ("DAILEKHI", "दैलेखी"),
                            ("LHOPA", "ल्होपा"),
                            ("DURA", "दुरा"),
                            ("KOCHE", "कोचे"),
                            ("CHILING", "छिलिङ"),
                            ("ENGLISH", "अंग्रेजी"),
                            ("JERO", "जेरो/जेरूङ"),
                            ("KHAS", "खस"),
                            ("SANSKRIT", "संस्कृत"),
                            ("DOLPALI", "डोल्पाली"),
                            ("HAYU", "हायू/भायू"),
                            ("TILUNG", "तिलुङ"),
                            ("KOYI", "कोयी"),
                            ("KISAN", "किसान"),
                            ("WALING", "वालिङ/वालुङ"),
                            ("MUSALMAN", "मुसल्मान"),
                            ("HIRAYANWI", "हिरयान्वी"),
                            ("JUMLI", "जुम्ली"),
                            ("PUNJABI", "पन्जाबी"),
                            ("LHOMI", "ल्होमी"),
                            ("BELHARI", "बेल्हारे"),
                            ("ORIYA", "ओरिया"),
                            ("SONAHA", "सोनहा"),
                            ("SINDHI", "सिन्धी"),
                            ("DADELDHURI", "डडेल्धुरी"),
                            ("BYANSI", "ब्याँसी"),
                            ("AASAMI", "आसामी"),
                            ("KAHMCHI", "खाम्ची/राउटे"),
                            ("SAAM", "साम"),
                            ("MANAGE", "मनाङ्गे"),
                            ("DHULELI", "धुलेली"),
                            ("PHANGDUWALI", "फाङ्दुवाली"),
                            ("SUREL", "सुरेल"),
                            ("MALPANDE", "माल्पाण्डे"),
                            ("CHINESE", "चाइनिज"),
                            ("KHARIYA", "खरिया"),
                            ("KURMALI", "कुर्माली"),
                            ("BARAM", "बराम"),
                            ("LINGKHIM", "लिङखिम"),
                            ("SADHANI", "सधनी"),
                            ("KAGATE", "कागते"),
                            ("JONGKHA", "जोङ्खा"),
                            ("BANKARIYA", "बनकरिया"),
                            ("KAIKE", "काइके"),
                            ("GADHWALI", "पोखराली"),
                            ("FRECHN", "फ्रेन्च/फ्रान्सेली"),
                            ("MIJO", "मिजो"),
                            ("KUKI", "कुकी"),
                            ("KUSUNDA", "कुसुण्डा"),
                            ("RUSSIAN", "रसियन"),
                            ("SPANISH", "स्पेनिस"),
                            ("NAGAMIJ", "नगामिज"),
                            ("ARABI", "अरबी"),
                            ("OTHER", "अन्य (खुलाउने)"),
                        ],
                        max_length=50,
                        verbose_name="मातृभाषा",
                    ),
                ),
                ("population", models.PositiveIntegerField(verbose_name="जनसंख्या")),
            ],
            options={
                "verbose_name": "मातृभाषा विवरण",
                "verbose_name_plural": "मातृभाषा विवरण",
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideReligionPopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("HINDU", "हिन्दू"),
                            ("BUDDHIST", "बौद्ध"),
                            ("KIRANT", "किरात"),
                            ("CHRISTIAN", "क्रिश्चियन"),
                            ("ISLAM", "इस्लाम"),
                            ("NATURE", "प्रकृति"),
                            ("BON", "बोन"),
                            ("JAIN", "जैन"),
                            ("BAHAI", "बहाई"),
                            ("SIKH", "सिख"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=50,
                        verbose_name="धर्म",
                    ),
                ),
                ("population", models.PositiveIntegerField(verbose_name="जनसंख्या")),
            ],
            options={
                "verbose_name": "धर्म विवरण",
                "verbose_name_plural": "धर्म विवरण",
            },
        ),
        migrations.CreateModel(
            name="WardAgeGenderWiseDeceasedPopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("AGE_0_4", "०-४ वर्ष"),
                            ("AGE_5_9", "५-९ वर्ष"),
                            ("AGE_10_14", "१०-१४ वर्ष"),
                            ("AGE_15_19", "१५-१९ वर्ष"),
                            ("AGE_20_24", "२०-२४ वर्ष"),
                            ("AGE_25_29", "२५-२९ वर्ष"),
                            ("AGE_30_34", "३०-३४ वर्ष"),
                            ("AGE_35_39", "३५-३९ वर्ष"),
                            ("AGE_40_44", "४०-४४ वर्ष"),
                            ("AGE_45_49", "४५-४९ वर्ष"),
                            ("AGE_50_54", "५०-५४ वर्ष"),
                            ("AGE_55_59", "५५-५९ वर्ष"),
                            ("AGE_60_64", "६०-६४ वर्ष"),
                            ("AGE_65_69", "६५-६९ वर्ष"),
                            ("AGE_70_74", "७०-७४ वर्ष"),
                            ("AGE_75_AND_ABOVE", "७५ वर्षभन्दा माथि"),
                        ],
                        max_length=20,
                        verbose_name="उमेर समूह",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "पुरुष"),
                            ("FEMALE", "महिला"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=10,
                        verbose_name="लिङ्ग",
                    ),
                ),
                (
                    "deceased_population",
                    models.PositiveIntegerField(verbose_name="मृत्यु जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत उमेर लिङ्गअनुसार मृत्यु जनसंख्या",
                "verbose_name_plural": "वडागत उमेर लिङ्गअनुसार मृत्यु जनसंख्या",
                "unique_together": {("ward_number", "age_group", "gender")},
            },
        ),
        migrations.CreateModel(
            name="WardAgeWiseEconomicallyActivePopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("AGE_0_TO_14", "०-१४ वर्ष"),
                            ("AGE_15_TO_59", "१५-५९ वर्ष"),
                            ("AGE_60_PLUS", "६० वर्ष माथि"),
                        ],
                        max_length=20,
                        verbose_name="उमेर समूह",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "पुरुष"),
                            ("FEMALE", "महिला"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="लिङ्ग",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(verbose_name="आर्थिक रूपमा सक्रिय जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत उमेर र लिङ्गअनुसार आर्थिक रूपमा सक्रिय जनसंख्या",
                "verbose_name_plural": "वडागत उमेर र लिङ्गअनुसार आर्थिक रूपमा सक्रिय जनसंख्या",
                "unique_together": {("ward_number", "age_group", "gender")},
            },
        ),
        migrations.CreateModel(
            name="WardAgeWisePopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("AGE_0_4", "०-४ वर्ष"),
                            ("AGE_5_9", "५-९ वर्ष"),
                            ("AGE_10_14", "१०-१४ वर्ष"),
                            ("AGE_15_19", "१५-१९ वर्ष"),
                            ("AGE_20_24", "२०-२४ वर्ष"),
                            ("AGE_25_29", "२५-२९ वर्ष"),
                            ("AGE_30_34", "३०-३४ वर्ष"),
                            ("AGE_35_39", "३५-३९ वर्ष"),
                            ("AGE_40_44", "४०-४४ वर्ष"),
                            ("AGE_45_49", "४५-४९ वर्ष"),
                            ("AGE_50_54", "५०-५४ वर्ष"),
                            ("AGE_55_59", "५५-५९ वर्ष"),
                            ("AGE_60_64", "६०-६४ वर्ष"),
                            ("AGE_65_69", "६५-६९ वर्ष"),
                            ("AGE_70_74", "७०-७४ वर्ष"),
                            ("AGE_75_AND_ABOVE", "७५ वर्षभन्दा माथि"),
                        ],
                        max_length=20,
                        verbose_name="उमेर समूह",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "पुरुष"),
                            ("FEMALE", "महिला"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=10,
                        verbose_name="लिङ्ग",
                    ),
                ),
                ("population", models.PositiveIntegerField(verbose_name="जनसंख्या")),
            ],
            options={
                "verbose_name": "वडागत उमेरगत जनसंख्या",
                "verbose_name_plural": "वडागत उमेरगत जनसंख्या",
                "unique_together": {("ward_number", "age_group", "gender")},
            },
        ),
        migrations.CreateModel(
            name="WardSettlement",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "settlement_areas",
                    models.JSONField(
                        blank=True, default=list, verbose_name="मुख्य बस्तीहरु"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत बस्ती विवरण",
                "verbose_name_plural": "वडागत बस्ती विवरण",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardTimeSeriesPopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "ward_name",
                    models.TextField(blank=True, null=True, verbose_name="वडाको नाम"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="वर्ष")),
                (
                    "total_population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="कुल जनसंख्या"
                    ),
                ),
                (
                    "male_population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="पुरुष जनसंख्या"
                    ),
                ),
                (
                    "female_population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="महिला जनसंख्या"
                    ),
                ),
                (
                    "other_population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="अन्य जनसंख्या"
                    ),
                ),
                (
                    "total_households",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="कुल घरपरिवार"
                    ),
                ),
                (
                    "average_household_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="औसत घरपरिवार आकार",
                    ),
                ),
                (
                    "population_0_to_14",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="०-१४ वर्ष जनसंख्या"
                    ),
                ),
                (
                    "population_15_to_59",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="१५-५९ वर्ष जनसंख्या"
                    ),
                ),
                (
                    "population_60_and_above",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="६० वर्षभन्दा माथि जनसंख्या"
                    ),
                ),
                (
                    "literacy_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="साक्षरता दर",
                    ),
                ),
                (
                    "male_literacy_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="पुरुष साक्षरता दर",
                    ),
                ),
                (
                    "female_literacy_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="महिला साक्षरता दर",
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="वृद्धि दर",
                    ),
                ),
                (
                    "area_sq_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="क्षेत्रफल (वर्ग कि.मी.)",
                    ),
                ),
                (
                    "population_density",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="जनसंख्या घनत्व",
                    ),
                ),
                (
                    "sex_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="लिङ्ग अनुपात",
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत समयश्रृंखला जनसंख्या",
                "verbose_name_plural": "वडागत समयश्रृंखला जनसंख्या",
                "unique_together": {("ward_number", "year")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseBirthCertificatePopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "with_birth_certificate",
                    models.PositiveIntegerField(verbose_name="जन्म दर्ता भएका"),
                ),
                (
                    "without_birth_certificate",
                    models.PositiveIntegerField(verbose_name="जन्म दर्ता नभएका"),
                ),
                (
                    "total_population_under_5",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="५ वर्षमुनिका कुल बालबालिका"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत जन्म दर्ता जनसंख्या",
                "verbose_name_plural": "वडागत जन्म दर्ता जनसंख्या",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseBirthplaceHouseholds",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(
                        choices=[
                            ("SAME_MUNICIPALITY", "यहि गापा/नपा"),
                            (
                                "SAME_DISTRICT_ANOTHER_MUNICIPALITY",
                                "यहि जिल्लाको अर्को गा.पा./न.पा",
                            ),
                            ("ANOTHER_DISTRICT", "अर्को जिल्ला"),
                            ("ABROAD", "विदेश"),
                        ],
                        max_length=50,
                        verbose_name="जन्मस्थान",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(verbose_name="घरपरिवार संख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत जन्मस्थानअनुसार घरपरिवार",
                "verbose_name_plural": "वडागत जन्मस्थानअनुसार घरपरिवार",
                "unique_together": {("ward_number", "birth_place")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseDeathCause",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "death_cause",
                    models.CharField(
                        choices=[
                            ("CANCER", "क्यान्सर"),
                            ("DEATH_BY_OLD_AGE", "कालगतिले"),
                            ("HEART_RELATED_DISEASES", "मुटु सम्बन्धी रोग"),
                            (
                                "BLOOD_PRESSURE_HIGH_AND_LOW_BLOOD_PRESSURE",
                                "रक्तचाप (उच्च/निम्न)",
                            ),
                            ("PNEUMONIA", "निमोनिया"),
                            ("ASTHMA", "दमा"),
                            ("DIABETES", "मधुमेह"),
                            ("KIDNEY_RELATED_DISEASES", "मिर्गौला सम्बन्धी रोग"),
                            ("LIVER_RELATED_DISEASES", "कलेजो सम्बन्धी रोग"),
                            ("TYPHOID", "टाइफाइड"),
                            ("FLU", "फ्लु"),
                            ("SUICIDE", "आत्महत्या"),
                            ("TRAFFIC_ACCIDENT", "सवारी दुर्घटना"),
                            ("OTHER_ACCIDENTS", "अन्य दुर्घटना"),
                            ("NATURAL_DISASTER", "प्राकृतिक प्रकोप"),
                            ("NOT_STATED", "कारण नखुलेको"),
                            ("LEPROSY", "कुष्ठरोग"),
                            ("KALA_AZAR", "कालाजार"),
                            ("RESPIRATORY_DISEASES", "श्वासप्रश्वास सम्बन्धी रोग"),
                            (
                                "GASTRIC_ULCER_INTESTINAL_DISEASE",
                                "ग्यास्ट्रिक/आन्द्रा सम्बन्धी रोग",
                            ),
                            ("EPILEPSY", "मिर्गी"),
                            ("TUBERCULOSIS", "क्षयरोग"),
                            ("SCABIES", "खटिरा"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=50,
                        verbose_name="मृत्युको कारण",
                    ),
                ),
                ("population", models.PositiveIntegerField(verbose_name="जनसंख्या")),
            ],
            options={
                "verbose_name": "वडागत मृत्युको कारण",
                "verbose_name_plural": "वडागत मृत्युको कारण",
                "unique_together": {("ward_number", "death_cause")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseDisabilityCause",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "disability_cause",
                    models.CharField(
                        choices=[
                            ("CONGENITAL", "जन्मजात"),
                            ("ACCIDENT", "दुर्घटना"),
                            ("MALNUTRITION", "कुपोषण"),
                            ("DISEASE", "रोगको कारण"),
                            ("CONFLICT", "द्वन्द्वको कारण"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="अपाङ्गताको कारण",
                    ),
                ),
                ("population", models.PositiveIntegerField(verbose_name="जनसंख्या")),
            ],
            options={
                "verbose_name": "वडागत अपाङ्गताको कारण",
                "verbose_name_plural": "वडागत अपाङ्गताको कारण",
                "unique_together": {("ward_number", "disability_cause")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseFemalePropertyOwnership",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("HOUSE_ONLY", "घर मात्र"),
                            ("LAND_ONLY", "जग्गा मात्र"),
                            ("BOTH_HOUSE_AND_LAND", "घर र जग्गा दुवै"),
                            ("NEITHER_HOUSE_NOR_LAND", "घर र जग्गा कुनै पनि छैन"),
                        ],
                        max_length=50,
                        verbose_name="सम्पत्तिको प्रकार",
                    ),
                ),
                ("count", models.PositiveIntegerField(verbose_name="गणना")),
                ("population", models.PositiveIntegerField(verbose_name="जनसंख्या")),
            ],
            options={
                "verbose_name": "वडागत महिला सम्पत्ति स्वामित्व",
                "verbose_name_plural": "वडागत महिला सम्पत्ति स्वामित्व",
                "unique_together": {("ward_number", "property_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseheadGender",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "ward_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="वडाको नाम"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "पुरुष"),
                            ("FEMALE", "महिला"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=10,
                        verbose_name="घरमुखियाको लिङ्ग",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(verbose_name="घरपरिवार संख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत घरमुखियाको लिङ्ग",
                "verbose_name_plural": "वडागत घरमुखियाको लिङ्ग",
                "unique_together": {("ward_number", "gender")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseMajorOccupation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("ANIMAL_HUSBANDRY", "पशुपालन"),
                            ("BUSINESS", "व्यापर"),
                            ("DAILY_WAGE", "दैनिक मजदुरी"),
                            ("FOREIGN_EMPLOYMENT", "वैदेशिक रोजगार"),
                            ("GOVERNMENT_SERVICE", "सरकारी सेवा"),
                            ("HOUSEHOLD_WORK", "घरेलु काम"),
                            ("INDUSTRY", "उद्योग"),
                            ("NON_GOVERNMENT_SERVICE", "गैर सरकारी सेवा"),
                            ("OTHER", "अन्य"),
                            ("OTHER_SELF_EMPLOYMENT", "अन्य स्व रोजगार"),
                            ("OTHER_UNEMPLOYMENT", "अन्य बेरोजगार"),
                            ("STUDENT", "विद्यार्थी"),
                        ],
                        max_length=50,
                        verbose_name="पेशा",
                    ),
                ),
                ("population", models.PositiveIntegerField(verbose_name="जनसंख्या")),
            ],
            options={
                "verbose_name": "वडागत मुख्य पेशा",
                "verbose_name_plural": "वडागत मुख्य पेशा",
                "unique_together": {("ward_number", "occupation")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseMigratedHouseholds",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "migrated_from",
                    models.CharField(
                        choices=[
                            ("ANOTHER_DISTRICT", "नेपालको अर्को जिल्ला"),
                            (
                                "SAME_DISTRICT_ANOTHER_MUNICIPALITY",
                                "यही जिल्लाको अर्को स्थानीय तह",
                            ),
                            ("ABROAD", "विदेश"),
                        ],
                        max_length=50,
                        verbose_name="बसाइसराइको स्थान",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(verbose_name="घरपरिवार संख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत बसाइसराइ गरेका घरपरिवार",
                "verbose_name_plural": "वडागत बसाइसराइ गरेका घरपरिवार",
                "unique_together": {("ward_number", "migrated_from")},
            },
        ),
    ]
