# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PoliticalStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "ward_name",
                    models.CharField(max_length=200, verbose_name="वडाको नाम"),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2070),
                            django.core.validators.MaxValueValidator(2090),
                        ],
                        verbose_name="वर्ष",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="जनसंख्या",
                    ),
                ),
            ],
            options={
                "verbose_name": "राजनैतिक अवस्था",
                "verbose_name_plural": "राजनैतिक अवस्थाहरू",
                "ordering": ["ward_number", "year"],
                "unique_together": {("ward_number", "year")},
            },
        ),
    ]
