-- Check if acme_ward_wise_death_cause table exists, if not create it
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_tables WHERE tablename = 'acme_ward_wise_death_cause'
    ) THEN
        CREATE TABLE acme_ward_wise_death_cause (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            ward_number INTEGER NOT NULL,
            death_cause TEXT NOT NULL,
            population INTEGER NOT NULL DEFAULT 0 CHECK (population >= 0),
            updated_at TIMESTAMP DEFAULT NOW(),
            created_at TIMESTAMP DEFAULT NOW()
        );
    END IF;
END
$$;

-- Insert seed data if table is empty
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM acme_ward_wise_death_cause) THEN
        INSERT INTO acme_ward_wise_death_cause (
            ward_number, death_cause, population
        )
        VALUES
        -- Data from the provided table
        (1, 'OTHER', 1),
        (2, 'OTHER', 11),
        (3, 'OTHER', 4),
        (4, 'OTHER', 4),
        (5, 'OTHER', 5),
        (6, 'OTHER', 6),
        (7, 'OTHER', 1),
        (8, 'OTHER', 3),

        (1, 'DEATH_BY_OLD_AGE', 1),
        (2, 'DEATH_BY_OLD_AGE', 6),
        (3, 'DEATH_BY_OLD_AGE', 1),
        (4, 'DEATH_BY_OLD_AGE', 0),
        (5, 'DEATH_BY_OLD_AGE', 4),
        (6, 'DEATH_BY_OLD_AGE', 6),
        (7, 'DEATH_BY_OLD_AGE', 9),
        (8, 'DEATH_BY_OLD_AGE', 0),

        (1, 'BLOOD_PRESSURE', 4),
        (2, 'BLOOD_PRESSURE', 8),
        (3, 'BLOOD_PRESSURE', 2),
        (4, 'BLOOD_PRESSURE', 1),
        (5, 'BLOOD_PRESSURE', 0),
        (6, 'BLOOD_PRESSURE', 3),
        (7, 'BLOOD_PRESSURE', 0),
        (8, 'BLOOD_PRESSURE', 1),

        (1, 'CANCER', 1),
        (2, 'CANCER', 7),
        (3, 'CANCER', 3),
        (4, 'CANCER', 1),
        (5, 'CANCER', 0),
        (6, 'CANCER', 6),
        (7, 'CANCER', 0),
        (8, 'CANCER', 1),

        (1, 'RESPIRATORY_DISEASES', 3),
        (2, 'RESPIRATORY_DISEASES', 6),
        (3, 'RESPIRATORY_DISEASES', 1),
        (4, 'RESPIRATORY_DISEASES', 0),
        (5, 'RESPIRATORY_DISEASES', 2),
        (6, 'RESPIRATORY_DISEASES', 2),
        (7, 'RESPIRATORY_DISEASES', 2),
        (8, 'RESPIRATORY_DISEASES', 1),

        (1, 'ASTHMA', 3),
        (2, 'ASTHMA', 2),
        (3, 'ASTHMA', 0),
        (4, 'ASTHMA', 1),
        (5, 'ASTHMA', 0),
        (6, 'ASTHMA', 6),
        (7, 'ASTHMA', 1),
        (8, 'ASTHMA', 0),

        (1, 'KIDNEY_RELATED_DISEASES', 0),
        (2, 'KIDNEY_RELATED_DISEASES', 3),
        (3, 'KIDNEY_RELATED_DISEASES', 1),
        (4, 'KIDNEY_RELATED_DISEASES', 1),
        (5, 'KIDNEY_RELATED_DISEASES', 0),
        (6, 'KIDNEY_RELATED_DISEASES', 0),
        (7, 'KIDNEY_RELATED_DISEASES', 1),
        (8, 'KIDNEY_RELATED_DISEASES', 2),

        (1, 'HEART_RELATED_DISEASES', 1),
        (2, 'HEART_RELATED_DISEASES', 2),
        (3, 'HEART_RELATED_DISEASES', 1),
        (4, 'HEART_RELATED_DISEASES', 0),
        (5, 'HEART_RELATED_DISEASES', 0),
        (6, 'HEART_RELATED_DISEASES', 4),
        (7, 'HEART_RELATED_DISEASES', 0),
        (8, 'HEART_RELATED_DISEASES', 0),

        (1, 'BRAIN_RELATED', 2),
        (2, 'BRAIN_RELATED', 3),
        (3, 'BRAIN_RELATED', 0),
        (4, 'BRAIN_RELATED', 1),
        (5, 'BRAIN_RELATED', 0),
        (6, 'BRAIN_RELATED', 0),
        (7, 'BRAIN_RELATED', 0),
        (8, 'BRAIN_RELATED', 1),

        (1, 'PNEUMONIA', 1),
        (2, 'PNEUMONIA', 0),
        (3, 'PNEUMONIA', 0),
        (4, 'PNEUMONIA', 2),
        (5, 'PNEUMONIA', 2),
        (6, 'PNEUMONIA', 0),
        (7, 'PNEUMONIA', 0),
        (8, 'PNEUMONIA', 1),

        (1, 'TRAFFIC_ACCIDENT', 0),
        (2, 'TRAFFIC_ACCIDENT', 3),
        (3, 'TRAFFIC_ACCIDENT', 0),
        (4, 'TRAFFIC_ACCIDENT', 0),
        (5, 'TRAFFIC_ACCIDENT', 0),
        (6, 'TRAFFIC_ACCIDENT', 2),
        (7, 'TRAFFIC_ACCIDENT', 1),
        (8, 'TRAFFIC_ACCIDENT', 0),

        (1, 'JAUNDICE_HEPATITIS', 1),
        (2, 'JAUNDICE_HEPATITIS', 1),
        (3, 'JAUNDICE_HEPATITIS', 2),
        (4, 'JAUNDICE_HEPATITIS', 0),
        (5, 'JAUNDICE_HEPATITIS', 0),
        (6, 'JAUNDICE_HEPATITIS', 1),
        (7, 'JAUNDICE_HEPATITIS', 0),
        (8, 'JAUNDICE_HEPATITIS', 0),

        (1, 'DIABETES', 4),
        (2, 'DIABETES', 0),
        (3, 'DIABETES', 0),
        (4, 'DIABETES', 0),
        (5, 'DIABETES', 0),
        (6, 'DIABETES', 1),
        (7, 'DIABETES', 0),
        (8, 'DIABETES', 0),

        (1, 'TYPHOID', 0),
        (2, 'TYPHOID', 0),
        (3, 'TYPHOID', 0),
        (4, 'TYPHOID', 1),
        (5, 'TYPHOID', 1),
        (6, 'TYPHOID', 1),
        (7, 'TYPHOID', 1),
        (8, 'TYPHOID', 2),

        (1, 'HAIJA', 0),
        (2, 'HAIJA', 0),
        (3, 'HAIJA', 0),
        (4, 'HAIJA', 0),
        (5, 'HAIJA', 5),
        (6, 'HAIJA', 0),
        (7, 'HAIJA', 0),
        (8, 'HAIJA', 0),

        (1, 'LIVER_RELATED_DISEASES', 0),
        (2, 'LIVER_RELATED_DISEASES', 1),
        (3, 'LIVER_RELATED_DISEASES', 2),
        (4, 'LIVER_RELATED_DISEASES', 1),
        (5, 'LIVER_RELATED_DISEASES', 0),
        (6, 'LIVER_RELATED_DISEASES', 0),
        (7, 'LIVER_RELATED_DISEASES', 1),
        (8, 'LIVER_RELATED_DISEASES', 0),

        (1, 'OTHER_ACCIDENT', 0),
        (2, 'OTHER_ACCIDENT', 3),
        (3, 'OTHER_ACCIDENT', 0),
        (4, 'OTHER_ACCIDENT', 0),
        (5, 'OTHER_ACCIDENT', 0),
        (6, 'OTHER_ACCIDENT', 0),
        (7, 'OTHER_ACCIDENT', 0),
        (8, 'OTHER_ACCIDENT', 0),

        (1, 'OTHER_SEXUALLY_TRANSMITTED_DISEASES', 1),
        (2, 'OTHER_SEXUALLY_TRANSMITTED_DISEASES', 0),
        (3, 'OTHER_SEXUALLY_TRANSMITTED_DISEASES', 0),
        (4, 'OTHER_SEXUALLY_TRANSMITTED_DISEASES', 1),
        (5, 'OTHER_SEXUALLY_TRANSMITTED_DISEASES', 1),
        (6, 'OTHER_SEXUALLY_TRANSMITTED_DISEASES', 0),
        (7, 'OTHER_SEXUALLY_TRANSMITTED_DISEASES', 0),
        (8, 'OTHER_SEXUALLY_TRANSMITTED_DISEASES', 1),

        (1, 'SUICIDE', 2),
        (2, 'SUICIDE', 0),
        (3, 'SUICIDE', 0),
        (4, 'SUICIDE', 1),
        (5, 'SUICIDE', 0),
        (6, 'SUICIDE', 0),
        (7, 'SUICIDE', 0),
        (8, 'SUICIDE', 0),

        (1, 'KALA_AZAR', 0),
        (2, 'KALA_AZAR', 1),
        (3, 'KALA_AZAR', 0),
        (4, 'KALA_AZAR', 1),
        (5, 'KALA_AZAR', 0),
        (6, 'KALA_AZAR', 0),
        (7, 'KALA_AZAR', 1),
        (8, 'KALA_AZAR', 0),

        (1, 'LEPROSY', 0),
        (2, 'LEPROSY', 0),
        (3, 'LEPROSY', 0),
        (4, 'LEPROSY', 3),
        (5, 'LEPROSY', 0),
        (6, 'LEPROSY', 0),
        (7, 'LEPROSY', 0),
        (8, 'LEPROSY', 0),

        (1, 'GASTRIC_ULCER_INTESTINAL_DISEASE', 1),
        (2, 'GASTRIC_ULCER_INTESTINAL_DISEASE', 1),
        (3, 'GASTRIC_ULCER_INTESTINAL_DISEASE', 0),
        (4, 'GASTRIC_ULCER_INTESTINAL_DISEASE', 0),
        (5, 'GASTRIC_ULCER_INTESTINAL_DISEASE', 0),
        (6, 'GASTRIC_ULCER_INTESTINAL_DISEASE', 0),
        (7, 'GASTRIC_ULCER_INTESTINAL_DISEASE', 0),
        (8, 'GASTRIC_ULCER_INTESTINAL_DISEASE', 0),

        (1, 'REPRODUCTIVE_OR_OBSTETRIC_CAUSES', 0),
        (2, 'REPRODUCTIVE_OR_OBSTETRIC_CAUSES', 1),
        (3, 'REPRODUCTIVE_OR_OBSTETRIC_CAUSES', 1),
        (4, 'REPRODUCTIVE_OR_OBSTETRIC_CAUSES', 0),
        (5, 'REPRODUCTIVE_OR_OBSTETRIC_CAUSES', 0),
        (6, 'REPRODUCTIVE_OR_OBSTETRIC_CAUSES', 0),
        (7, 'REPRODUCTIVE_OR_OBSTETRIC_CAUSES', 0),
        (8, 'REPRODUCTIVE_OR_OBSTETRIC_CAUSES', 0),

        (1, 'FLU', 0),
        (2, 'FLU', 1),
        (3, 'FLU', 1),
        (4, 'FLU', 0),
        (5, 'FLU', 0),
        (6, 'FLU', 0),
        (7, 'FLU', 0),
        (8, 'FLU', 0),

        (1, 'OTHER_INFECTIOUS_DISEASES', 0),
        (2, 'OTHER_INFECTIOUS_DISEASES', 0),
        (3, 'OTHER_INFECTIOUS_DISEASES', 0),
        (4, 'OTHER_INFECTIOUS_DISEASES', 1),
        (5, 'OTHER_INFECTIOUS_DISEASES', 1),
        (6, 'OTHER_INFECTIOUS_DISEASES', 0),
        (7, 'OTHER_INFECTIOUS_DISEASES', 0),
        (8, 'OTHER_INFECTIOUS_DISEASES', 0),

        (1, 'TUBERCULOSIS', 0),
        (2, 'TUBERCULOSIS', 0),
        (3, 'TUBERCULOSIS', 0),
        (4, 'TUBERCULOSIS', 0),
        (5, 'TUBERCULOSIS', 1),
        (6, 'TUBERCULOSIS', 0),
        (7, 'TUBERCULOSIS', 0),
        (8, 'TUBERCULOSIS', 0),

        (1, 'HEPATITIS', 0),
        (2, 'HEPATITIS', 0),
        (3, 'HEPATITIS', 0),
        (4, 'HEPATITIS', 0),
        (5, 'HEPATITIS', 0),
        (6, 'HEPATITIS', 1),
        (7, 'HEPATITIS', 0),
        (8, 'HEPATITIS', 0);
    END IF;
END
$$;
