# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "प्रशासक"),
                            ("manager", "प्रबन्धक"),
                            ("data_entry", "डाटा एन्ट्री"),
                            ("viewer", "दर्शक"),
                            ("ward_officer", "वडा अधिकारी"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="भूमिका",
                    ),
                ),
                (
                    "full_name_nepali",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="पूरा नाम (नेपालीमा)",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="फोन नम्बर"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="पद"
                    ),
                ),
                (
                    "position_nepali",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="पद (नेपालीमा)",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="विभाग"
                    ),
                ),
                (
                    "ward_number",
                    models.IntegerField(
                        blank=True,
                        help_text="वडा अधिकारीहरूका लागि मात्र",
                        null=True,
                        verbose_name="वडा नं",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/profiles/",
                        verbose_name="प्रोफाइल फोटो",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="प्रमाणित"),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="अन्तिम पासवर्ड परिवर्तन"
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(default=0, verbose_name="असफल लगइन प्रयासहरू"),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="खाता लक गरिएको मिति"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "प्रयोगकर्ता",
                "verbose_name_plural": "प्रयोगकर्ताहरू",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_manage_demographics", "Can manage demographic data"),
                    ("can_manage_economics", "Can manage economic data"),
                    ("can_manage_social", "Can manage social data"),
                    ("can_manage_environment", "Can manage environment data"),
                    ("can_manage_infrastructure", "Can manage infrastructure data"),
                    ("can_manage_governance", "Can manage governance data"),
                    ("can_generate_reports", "Can generate reports"),
                    ("can_export_data", "Can export data"),
                    ("can_manage_users", "Can manage users"),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="सेसन कुञ्जी"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP ठेगाना")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="प्रयोगकर्ता एजेन्ट"),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="लगइन समय"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="लगआउट समय"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="सक्रिय")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="प्रयोगकर्ता",
                    ),
                ),
            ],
            options={
                "verbose_name": "प्रयोगकर्ता सेसन",
                "verbose_name_plural": "प्रयोगकर्ता सेसनहरू",
                "ordering": ["-login_time"],
            },
        ),
    ]
