# Generated by Django 5.2.3 on 2025-06-23 13:49

import ckeditor.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(default="पोखरा महानगरपालिका", max_length=200),
                ),
                (
                    "municipality_name_english",
                    models.CharField(
                        default="pokhara metropolitan city", max_length=200
                    ),
                ),
                (
                    "report_title",
                    models.CharField(default="डिजिटल प्रोफाइल प्रतिवेदन", max_length=300),
                ),
                (
                    "report_title_english",
                    models.CharField(default="Digital Profile Report", max_length=300),
                ),
                (
                    "publication_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="reports/logo/"),
                ),
                ("address", models.TextField(blank=True)),
                ("address_nepali", models.TextField(blank=True)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True, max_length=500)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("facebook_pixel_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Publication Settings",
                "verbose_name_plural": "Publication Settings",
            },
        ),
        migrations.CreateModel(
            name="ReportCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Category Name"),
                ),
                (
                    "name_nepali",
                    models.CharField(
                        max_length=200, verbose_name="Category Name (Nepali)"
                    ),
                ),
                (
                    "category_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Category Number (e.g., १)",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_nepali",
                    models.TextField(blank=True, verbose_name="Description (Nepali)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon Class"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report Category",
                "verbose_name_plural": "Report Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReportDownload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "download_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("full_report", "Full Report"),
                            ("section", "Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "downloaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Report Download",
                "verbose_name_plural": "Report Downloads",
            },
        ),
        migrations.CreateModel(
            name="ReportFigure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Figure Title"),
                ),
                (
                    "title_nepali",
                    models.CharField(
                        max_length=300, verbose_name="Figure Title (Nepali)"
                    ),
                ),
                (
                    "figure_type",
                    models.CharField(
                        choices=[
                            ("chart", "Chart"),
                            ("graph", "Graph"),
                            ("image", "Image"),
                            ("diagram", "Diagram"),
                            ("map", "Map"),
                        ],
                        default="chart",
                        max_length=20,
                    ),
                ),
                (
                    "figure_number",
                    models.CharField(max_length=20, verbose_name="Figure Number"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_nepali",
                    models.TextField(blank=True, verbose_name="Description (Nepali)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="reports/figures/"
                    ),
                ),
                (
                    "data_source",
                    models.TextField(blank=True, verbose_name="Data Source"),
                ),
                (
                    "chart_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Chart Data (JSON)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report Figure",
                "verbose_name_plural": "Report Figures",
                "ordering": ["section__category__order", "section__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Section Title"),
                ),
                (
                    "title_nepali",
                    models.CharField(
                        max_length=300, verbose_name="Section Title (Nepali)"
                    ),
                ),
                ("slug", models.SlugField(max_length=200)),
                (
                    "section_number",
                    models.CharField(
                        max_length=20, verbose_name="Section Number (e.g., 1.1)"
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Content"),
                ),
                (
                    "content_nepali",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Content (Nepali)"
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
                (
                    "summary_nepali",
                    models.TextField(blank=True, verbose_name="Summary (Nepali)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="SEO Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="SEO Keywords"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Report Section",
                "verbose_name_plural": "Report Sections",
                "ordering": ["category__order", "order", "section_number"],
            },
        ),
        migrations.CreateModel(
            name="ReportTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Table Title")),
                (
                    "title_nepali",
                    models.CharField(
                        max_length=300, verbose_name="Table Title (Nepali)"
                    ),
                ),
                (
                    "table_number",
                    models.CharField(max_length=20, verbose_name="Table Number"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_nepali",
                    models.TextField(blank=True, verbose_name="Description (Nepali)"),
                ),
                ("data", models.JSONField(verbose_name="Table Data (JSON)")),
                (
                    "data_source",
                    models.TextField(blank=True, verbose_name="Data Source"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report Table",
                "verbose_name_plural": "Report Tables",
                "ordering": ["section__category__order", "section__order", "order"],
            },
        ),
    ]
