# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsection",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportsection",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="reports.reportcategory",
            ),
        ),
        migrations.AddField(
            model_name="reportfigure",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="figures",
                to="reports.reportsection",
            ),
        ),
        migrations.AddField(
            model_name="reportdownload",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.reportsection",
            ),
        ),
        migrations.AddField(
            model_name="reporttable",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="reports.reportsection",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportsection",
            unique_together={("category", "slug")},
        ),
    ]
