-- Check if acme_ward_wise_foreign_employment_countries table exists, if not create it
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_tables WHERE tablename = 'acme_ward_wise_foreign_employment_countries'
    ) THEN
        CREATE TABLE acme_ward_wise_foreign_employment_countries (
            id VARCHAR(36) PRIMARY KEY,
            ward_number INTEGER NOT NULL,
            country VARCHAR(100) NOT NULL,
            population INTEGER NOT NULL,
            updated_at TIMESTAMP DEFAULT NOW(),
            created_at TIMESTAMP DEFAULT NOW()
        );
    END IF;
END
$$;

-- Delete existing data to ensure clean insertion
DO $$
BEGIN
    DELETE FROM acme_ward_wise_foreign_employment_countries;
END
$$;

-- Insert real data from the provided table
DO $$
BEGIN
    -- Ward 1 data
    INSERT INTO acme_ward_wise_foreign_employment_countries (id, ward_number, country, population)
    VALUES
        (gen_random_uuid(), 1, 'INDIA', 172),
        (gen_random_uuid(), 1, 'SAUDI_ARABIA', 34),
        (gen_random_uuid(), 1, 'DUBAI', 58),
        (gen_random_uuid(), 1, 'MALAYSIA', 36),
        (gen_random_uuid(), 1, 'QATAR', 31),
        (gen_random_uuid(), 1, 'KRVET', 9),
        (gen_random_uuid(), 1, 'JAPAN', 4),
        (gen_random_uuid(), 1, 'NEPAL', 5),
        (gen_random_uuid(), 1, 'UNITED_STATES_OF_AMERICA', 5),
        (gen_random_uuid(), 1, 'ROMANIA', 3),
        (gen_random_uuid(), 1, 'UNITED_NATIONS', 1),
        (gen_random_uuid(), 1, 'SOUTH_KOREA', 2),
        (gen_random_uuid(), 1, 'SOUTH_AFRICA', 1),
        (gen_random_uuid(), 1, 'NORTH_KOREA', 4),
        (gen_random_uuid(), 1, 'POLAND', 1),
        (gen_random_uuid(), 1, 'FAWNS', 1),
        (gen_random_uuid(), 1, 'ARSHATYA', 1),
        (gen_random_uuid(), 1, 'CONGO', 1),
        (gen_random_uuid(), 1, 'UKRAINE', 1),
        (gen_random_uuid(), 1, 'ITALY', 1),
    
    -- Ward 2 data
        (gen_random_uuid(), 2, 'INDIA', 412),
        (gen_random_uuid(), 2, 'SAUDI_ARABIA', 240),
        (gen_random_uuid(), 2, 'DUBAI', 164),
        (gen_random_uuid(), 2, 'MALAYSIA', 138),
        (gen_random_uuid(), 2, 'QATAR', 125),
        (gen_random_uuid(), 2, 'KRVET', 59),
        (gen_random_uuid(), 2, 'JAPAN', 34),
        (gen_random_uuid(), 2, 'NEPAL', 27),
        (gen_random_uuid(), 2, 'AUSTRALIA', 11),
        (gen_random_uuid(), 2, 'UNITED_STATES_OF_AMERICA', 10),
        (gen_random_uuid(), 2, 'ROMANIA', 13),
        (gen_random_uuid(), 2, 'PORTUGAL', 6),
        (gen_random_uuid(), 2, 'BAHRAIN', 8),
        (gen_random_uuid(), 2, 'CANADA', 4),
        (gen_random_uuid(), 2, 'UNITED_NATIONS', 5),
        (gen_random_uuid(), 2, 'MALTA', 4),
        (gen_random_uuid(), 2, 'SOUTH_KOREA', 3),
        (gen_random_uuid(), 2, 'CROATIA', 2),
        (gen_random_uuid(), 2, 'SOUTH_AFRICA', 6),
        (gen_random_uuid(), 2, 'NEW_ZEALAND', 6),
        (gen_random_uuid(), 2, 'NORTH_KOREA', 3),
        (gen_random_uuid(), 2, 'CYPRUS', 3),
        (gen_random_uuid(), 2, 'UNITED_KINGDOM_OF_GREAT_BRITAIN', 1),
        (gen_random_uuid(), 2, 'MALDIVES', 1),
        (gen_random_uuid(), 2, 'RUSSIA', 5),
        (gen_random_uuid(), 2, 'FAWNS', 1),
        (gen_random_uuid(), 2, 'BULGARIA', 1),
        (gen_random_uuid(), 2, 'COSTA_RICA', 1),
        (gen_random_uuid(), 2, 'YEMEN', 2),
        (gen_random_uuid(), 2, 'SRIDAN', 1),
        (gen_random_uuid(), 2, 'MAURITIUS', 3),
        (gen_random_uuid(), 2, 'SRI_LANKA', 3),
        (gen_random_uuid(), 2, 'KATHMANDU', 4),
        (gen_random_uuid(), 2, 'FINLAND', 2),
        (gen_random_uuid(), 2, 'NIGER', 1),
        (gen_random_uuid(), 2, 'THE_NETHERLANDS', 2),
        (gen_random_uuid(), 2, 'MOROCCO', 2),
        (gen_random_uuid(), 2, 'INTERPOL', 1),
        (gen_random_uuid(), 2, 'KENYA', 2),
        (gen_random_uuid(), 2, 'TURKEY', 2),
        (gen_random_uuid(), 2, 'IRAQ', 1),
        (gen_random_uuid(), 2, 'BOLIVIA', 1),
        (gen_random_uuid(), 2, 'LEBANON', 1),
        (gen_random_uuid(), 2, 'GERMANY', 1),
        (gen_random_uuid(), 2, 'BANGLADESH', 1),
        (gen_random_uuid(), 2, 'MONGOLIA', 1),
        (gen_random_uuid(), 2, 'UZBEKISTAN', 1),
        (gen_random_uuid(), 2, 'UNITED_ARAB_EMIRATES', 1),
        (gen_random_uuid(), 2, 'BELGIUM', 1),
        (gen_random_uuid(), 2, 'EGYPT', 1),
        (gen_random_uuid(), 2, 'REPUBLIC_OF_IRELAND', 1),
        (gen_random_uuid(), 2, 'HONG_KONG', 1),
        (gen_random_uuid(), 2, 'PHILIPPINES', 1),
        (gen_random_uuid(), 2, 'BURUNDI', 1),
        (gen_random_uuid(), 2, 'UGANDA', 1),
        (gen_random_uuid(), 2, 'AFGHANISTAN', 1),
        (gen_random_uuid(), 2, 'IRAN', 1),
        (gen_random_uuid(), 2, 'ARMENIA', 1),
    
    -- Ward 3 data
        (gen_random_uuid(), 3, 'INDIA', 258),
        (gen_random_uuid(), 3, 'SAUDI_ARABIA', 102),
        (gen_random_uuid(), 3, 'DUBAI', 118),
        (gen_random_uuid(), 3, 'MALAYSIA', 59),
        (gen_random_uuid(), 3, 'QATAR', 58),
        (gen_random_uuid(), 3, 'KRVET', 42),
        (gen_random_uuid(), 3, 'JAPAN', 29),
        (gen_random_uuid(), 3, 'NEPAL', 24),
        (gen_random_uuid(), 3, 'AUSTRALIA', 18),
        (gen_random_uuid(), 3, 'UNITED_STATES_OF_AMERICA', 19),
        (gen_random_uuid(), 3, 'ROMANIA', 8),
        (gen_random_uuid(), 3, 'PORTUGAL', 19),
        (gen_random_uuid(), 3, 'BAHRAIN', 5),
        (gen_random_uuid(), 3, 'CANADA', 7),
        (gen_random_uuid(), 3, 'UNITED_NATIONS', 6),
        (gen_random_uuid(), 3, 'MALTA', 4),
        (gen_random_uuid(), 3, 'SOUTH_KOREA', 2),
        (gen_random_uuid(), 3, 'CROATIA', 10),
        (gen_random_uuid(), 3, 'SOUTH_AFRICA', 1),
        (gen_random_uuid(), 3, 'NEW_ZEALAND', 7),
        (gen_random_uuid(), 3, 'NORTH_KOREA', 3),
        (gen_random_uuid(), 3, 'CYPRUS', 7),
        (gen_random_uuid(), 3, 'UNITED_KINGDOM_OF_GREAT_BRITAIN', 4),
        (gen_random_uuid(), 3, 'MALDIVES', 5),
        (gen_random_uuid(), 3, 'POLAND', 8),
        (gen_random_uuid(), 3, 'FAWNS', 6),
        (gen_random_uuid(), 3, 'ARSHATYA', 3),
        (gen_random_uuid(), 3, 'SOMALIA', 1),
        (gen_random_uuid(), 3, 'TOKYO', 5),
        (gen_random_uuid(), 3, 'BULGARIA', 4),
        (gen_random_uuid(), 3, 'YEMEN', 2),
        (gen_random_uuid(), 3, 'SINGAPORE', 1),
        (gen_random_uuid(), 3, 'SRIDAN', 2),
        (gen_random_uuid(), 3, 'SRI_LANKA', 1),
        (gen_random_uuid(), 3, 'FINLAND', 2),
        (gen_random_uuid(), 3, 'DENMARK', 1),
        (gen_random_uuid(), 3, 'ARUBA', 3),
        (gen_random_uuid(), 3, 'TAJIKISTAN', 1),
        (gen_random_uuid(), 3, 'CONGO', 1),
        (gen_random_uuid(), 3, 'CHINA', 2),
        (gen_random_uuid(), 3, 'GREECE', 1),
        (gen_random_uuid(), 3, 'CAMBODIA', 2),
        (gen_random_uuid(), 3, 'DUNGLAND', 2),
        (gen_random_uuid(), 3, 'LEBANON', 1),
        (gen_random_uuid(), 3, 'THAILAND', 1),
        (gen_random_uuid(), 3, 'VENEZUELA', 1),
        (gen_random_uuid(), 3, 'AZERBAIJAN', 1),
        (gen_random_uuid(), 3, 'SPAIN', 1),
        (gen_random_uuid(), 3, 'LUXEMBOURG', 1),
        (gen_random_uuid(), 3, 'MEXICO', 1),
        (gen_random_uuid(), 3, 'MYANMAR', 1),
        (gen_random_uuid(), 3, 'BRUNEI', 1),
        (gen_random_uuid(), 3, 'ITALY', 1),
    
    -- Ward 4 data
        (gen_random_uuid(), 4, 'INDIA', 462),
        (gen_random_uuid(), 4, 'SAUDI_ARABIA', 98),
        (gen_random_uuid(), 4, 'DUBAI', 99),
        (gen_random_uuid(), 4, 'MALAYSIA', 64),
        (gen_random_uuid(), 4, 'QATAR', 49),
        (gen_random_uuid(), 4, 'KRVET', 26),
        (gen_random_uuid(), 4, 'JAPAN', 18),
        (gen_random_uuid(), 4, 'NEPAL', 2),
        (gen_random_uuid(), 4, 'AUSTRALIA', 15),
        (gen_random_uuid(), 4, 'UNITED_STATES_OF_AMERICA', 6),
        (gen_random_uuid(), 4, 'ROMANIA', 7),
        (gen_random_uuid(), 4, 'PORTUGAL', 7),
        (gen_random_uuid(), 4, 'BAHRAIN', 2),
        (gen_random_uuid(), 4, 'CANADA', 3),
        (gen_random_uuid(), 4, 'UNITED_NATIONS', 5),
        (gen_random_uuid(), 4, 'MALTA', 9),
        (gen_random_uuid(), 4, 'SOUTH_KOREA', 3),
        (gen_random_uuid(), 4, 'CROATIA', 2),
        (gen_random_uuid(), 4, 'SOUTH_AFRICA', 4),
        (gen_random_uuid(), 4, 'NORTH_KOREA', 2),
        (gen_random_uuid(), 4, 'UNITED_KINGDOM_OF_GREAT_BRITAIN', 3),
        (gen_random_uuid(), 4, 'POLAND', 1),
        (gen_random_uuid(), 4, 'RUSSIA', 1),
        (gen_random_uuid(), 4, 'BITE', 4),
        (gen_random_uuid(), 4, 'ARSHATYA', 2),
        (gen_random_uuid(), 4, 'SOMALIA', 3),
        (gen_random_uuid(), 4, 'TOKYO', 1),
        (gen_random_uuid(), 4, 'COSTA_RICA', 4),
        (gen_random_uuid(), 4, 'SINGAPORE', 3),
        (gen_random_uuid(), 4, 'MACAU', 1),
        (gen_random_uuid(), 4, 'DENMARK', 2),
        (gen_random_uuid(), 4, 'THE_NETHERLANDS', 1),
        (gen_random_uuid(), 4, 'KENYA', 2),
        (gen_random_uuid(), 4, 'IRAQ', 2),
        (gen_random_uuid(), 4, 'MONGOLIA', 1),
        (gen_random_uuid(), 4, 'UZBEKISTAN', 1),
        (gen_random_uuid(), 4, 'THE_GARDENER', 1),
        (gen_random_uuid(), 4, 'SENEGAL', 1),
        (gen_random_uuid(), 4, 'SPAIN', 1),
        (gen_random_uuid(), 4, 'KOSOVO', 1),

    -- Ward 5 data
        (gen_random_uuid(), 5, 'INDIA', 5),
        (gen_random_uuid(), 5, 'SAUDI_ARABIA', 34),
        (gen_random_uuid(), 5, 'DUBAI', 7),
        (gen_random_uuid(), 5, 'MALAYSIA', 40),
        (gen_random_uuid(), 5, 'QATAR', 38),
        (gen_random_uuid(), 5, 'KRVET', 5),
        (gen_random_uuid(), 5, 'JAPAN', 1),
        (gen_random_uuid(), 5, 'NEPAL', 3),
        (gen_random_uuid(), 5, 'SRI_LANKA', 1),
        (gen_random_uuid(), 5, 'ISRAEL', 1),
        (gen_random_uuid(), 5, 'YUGOSLAVIA', 1),
        
    -- Ward 6 data
        (gen_random_uuid(), 6, 'INDIA', 569),
        (gen_random_uuid(), 6, 'SAUDI_ARABIA', 112),
        (gen_random_uuid(), 6, 'DUBAI', 69),
        (gen_random_uuid(), 6, 'MALAYSIA', 102),
        (gen_random_uuid(), 6, 'QATAR', 76),
        (gen_random_uuid(), 6, 'KRVET', 72),
        (gen_random_uuid(), 6, 'JAPAN', 4),
        (gen_random_uuid(), 6, 'NEPAL', 20),
        (gen_random_uuid(), 6, 'UNITED_STATES_OF_AMERICA', 1),
        (gen_random_uuid(), 6, 'ROMANIA', 2),
        (gen_random_uuid(), 6, 'PORTUGAL', 1),
        (gen_random_uuid(), 6, 'BAHRAIN', 3),
        (gen_random_uuid(), 6, 'UNITED_NATIONS', 1),
        (gen_random_uuid(), 6, 'SOUTH_KOREA', 3),
        (gen_random_uuid(), 6, 'UNITED_KINGDOM_OF_GREAT_BRITAIN', 2),
        (gen_random_uuid(), 6, 'ARSHATYA', 1),
        
    -- Ward 7 data
        (gen_random_uuid(), 7, 'INDIA', 98),
        (gen_random_uuid(), 7, 'SAUDI_ARABIA', 128),
        (gen_random_uuid(), 7, 'DUBAI', 34),
        (gen_random_uuid(), 7, 'MALAYSIA', 63),
        (gen_random_uuid(), 7, 'QATAR', 79),
        (gen_random_uuid(), 7, 'KRVET', 15),
        (gen_random_uuid(), 7, 'JAPAN', 8),
        (gen_random_uuid(), 7, 'NEPAL', 17),
        (gen_random_uuid(), 7, 'AUSTRALIA', 2),
        (gen_random_uuid(), 7, 'UNITED_STATES_OF_AMERICA', 1),
        (gen_random_uuid(), 7, 'ROMANIA', 6),
        (gen_random_uuid(), 7, 'PORTUGAL', 1),
        (gen_random_uuid(), 7, 'BAHRAIN', 2),
        (gen_random_uuid(), 7, 'CANADA', 5),
        (gen_random_uuid(), 7, 'MALTA', 1),
        (gen_random_uuid(), 7, 'SOUTH_KOREA', 2),
        (gen_random_uuid(), 7, 'SOUTH_AFRICA', 2),
        (gen_random_uuid(), 7, 'UNITED_KINGDOM_OF_GREAT_BRITAIN', 1),
        (gen_random_uuid(), 7, 'RUSSIA', 2),
        (gen_random_uuid(), 7, 'FAWNS', 1),
        (gen_random_uuid(), 7, 'MAURITIUS', 1),
        (gen_random_uuid(), 7, 'ISRAEL', 2),
        (gen_random_uuid(), 7, 'DENMARK', 2),
        (gen_random_uuid(), 7, 'TAJIKISTAN', 2),
        (gen_random_uuid(), 7, 'ALGERIA', 1),
        
    -- Ward 8 data
        (gen_random_uuid(), 8, 'INDIA', 117),
        (gen_random_uuid(), 8, 'SAUDI_ARABIA', 79),
        (gen_random_uuid(), 8, 'DUBAI', 41),
        (gen_random_uuid(), 8, 'MALAYSIA', 47),
        (gen_random_uuid(), 8, 'QATAR', 50),
        (gen_random_uuid(), 8, 'KRVET', 35),
        (gen_random_uuid(), 8, 'JAPAN', 17),
        (gen_random_uuid(), 8, 'NEPAL', 6),
        (gen_random_uuid(), 8, 'ROMANIA', 1),
        (gen_random_uuid(), 8, 'PORTUGAL', 2),
        (gen_random_uuid(), 8, 'BAHRAIN', 6),
        (gen_random_uuid(), 8, 'CROATIA', 1),
        (gen_random_uuid(), 8, 'NEW_ZEALAND', 1),
        (gen_random_uuid(), 8, 'MALDIVES', 1),
        (gen_random_uuid(), 8, 'RUSSIA', 1),
        (gen_random_uuid(), 8, 'FAWNS', 2),
        (gen_random_uuid(), 8, 'ARUBA', 2),
        (gen_random_uuid(), 8, 'NIGER', 3),
        (gen_random_uuid(), 8, 'INTERPOL', 1),
        (gen_random_uuid(), 8, 'TURKEY', 1),
        (gen_random_uuid(), 8, 'IRAQ', 2),
        (gen_random_uuid(), 8, 'LEBANON', 2);
END
$$;
