# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiodiversityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "species_name",
                    models.CharField(max_length=200, verbose_name="प्रजातिको नाम"),
                ),
                (
                    "species_name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="प्रजातिको नाम (नेपाली)"
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="वैज्ञानिक नाम"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "biodiversity_type",
                    models.CharField(
                        choices=[
                            ("MAMMALS", "स्तनधारी"),
                            ("BIRDS", "चराचुरुंगी"),
                            ("REPTILES", "सरीसृप"),
                            ("AMPHIBIANS", "उभयचर"),
                            ("FISH", "माछा"),
                            ("INSECTS", "कीराकीट"),
                            ("PLANTS", "वनस्पति"),
                            ("MEDICINAL_PLANTS", "जडिबुटी"),
                        ],
                        max_length=20,
                        verbose_name="जैविक विविधताको प्रकार",
                    ),
                ),
                (
                    "population_estimate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="जनसंख्या अनुमान"
                    ),
                ),
                (
                    "conservation_status",
                    models.CharField(
                        choices=[
                            ("ABUNDANT", "प्रचुर"),
                            ("COMMON", "सामान्य"),
                            ("RARE", "दुर्लभ"),
                            ("ENDANGERED", "लोपोन्मुख"),
                            ("CRITICALLY_ENDANGERED", "अति लोपोन्मुख"),
                            ("EXTINCT", "लुप्त"),
                        ],
                        default="COMMON",
                        max_length=30,
                        verbose_name="संरक्षण स्थिति",
                    ),
                ),
                (
                    "habitat_description",
                    models.TextField(blank=True, verbose_name="बासस्थान विवरण"),
                ),
                (
                    "economic_importance",
                    models.TextField(blank=True, verbose_name="आर्थिक महत्व"),
                ),
                ("threats", models.TextField(blank=True, verbose_name="खतराहरू")),
                (
                    "is_endemic",
                    models.BooleanField(default=False, verbose_name="स्थानीय प्रजाति हो"),
                ),
            ],
            options={
                "verbose_name": "जैविक विविधता अभिलेख",
                "verbose_name_plural": "जैविक विविधता अभिलेखहरू",
            },
        ),
        migrations.CreateModel(
            name="DisasterIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("incident_date", models.DateField(verbose_name="घटना मिति")),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "disaster_type",
                    models.CharField(
                        choices=[
                            ("EARTHQUAKE", "भूकम्प"),
                            ("LANDSLIDE", "पहिरो"),
                            ("FLOOD", "बाढी"),
                            ("FIRE", "आगलागी"),
                            ("DROUGHT", "खडेरी"),
                            ("HAILSTORM", "असिना"),
                            ("WIND_STORM", "आंधीबतास"),
                            ("LIGHTNING", "चट्याङ"),
                        ],
                        max_length=20,
                        verbose_name="विपद्को प्रकार",
                    ),
                ),
                (
                    "affected_households",
                    models.PositiveIntegerField(
                        default=0, verbose_name="प्रभावित घरपरिवार"
                    ),
                ),
                (
                    "affected_population",
                    models.PositiveIntegerField(
                        default=0, verbose_name="प्रभावित जनसंख्या"
                    ),
                ),
                (
                    "human_casualties",
                    models.PositiveIntegerField(default=0, verbose_name="मानवीय हानि"),
                ),
                (
                    "injured_count",
                    models.PositiveIntegerField(default=0, verbose_name="घाइते संख्या"),
                ),
                (
                    "houses_damaged",
                    models.PositiveIntegerField(default=0, verbose_name="क्षतिग्रस्त घर"),
                ),
                (
                    "economic_loss_npr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="आर्थिक हानि (रुपैयाँ)",
                    ),
                ),
                (
                    "crops_damaged_hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="बाली क्षति (हेक्टेयर)",
                    ),
                ),
                (
                    "livestock_lost",
                    models.PositiveIntegerField(default=0, verbose_name="पशु हानि"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="घटना विवरण"),
                ),
            ],
            options={
                "verbose_name": "विपद् घटना",
                "verbose_name_plural": "विपद् घटनाहरू",
            },
        ),
        migrations.CreateModel(
            name="EmergencyResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "resource_name",
                    models.CharField(max_length=200, verbose_name="स्रोतको नाम"),
                ),
                (
                    "resource_name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="स्रोतको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("AMBULANCE", "एम्बुलेन्स"),
                            ("FIRE_TRUCK", "फायर ब्रिगेड"),
                            ("RESCUE_VEHICLE", "उद्धार गाडी"),
                            ("EMERGENCY_SHELTER", "आपतकालीन आश्रय"),
                            ("RELIEF_STORE", "राहत भण्डार"),
                            ("COMMUNICATION_EQUIPMENT", "सञ्चार उपकरण"),
                            ("MEDICAL_SUPPLIES", "चिकित्सा सामग्री"),
                            ("WATER_TANKER", "पानी ट्यांकर"),
                            ("GENERATOR", "जेनेरेटर"),
                            ("RESCUE_EQUIPMENT", "उद्धार उपकरण"),
                        ],
                        max_length=30,
                        verbose_name="स्रोतको प्रकार",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="संख्या"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                            ("OUT_OF_ORDER", "बिग्रिएको"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="अवस्था",
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="सञ्चालनमा छ"),
                ),
                (
                    "responsible_organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="जिम्मेवार संस्था"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="सम्पर्क व्यक्ति"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="सम्पर्क नम्बर"
                    ),
                ),
            ],
            options={
                "verbose_name": "आपतकालीन स्रोत",
                "verbose_name_plural": "आपतकालीन स्रोतहरू",
            },
        ),
        migrations.CreateModel(
            name="ForestArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="वनको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="वनको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "forest_type",
                    models.CharField(
                        choices=[
                            ("DECIDUOUS", "पातलो वन"),
                            ("CONIFEROUS", "कोणधारी वन"),
                            ("MIXED", "मिश्रित वन"),
                            ("SHRUBLAND", "झाडीखण्ड"),
                            ("GRASSLAND", "घाँसे मैदान"),
                            ("BAMBOO", "बाँसको वन"),
                        ],
                        max_length=20,
                        verbose_name="वनको प्रकार",
                    ),
                ),
                (
                    "management_type",
                    models.CharField(
                        choices=[
                            ("GOVERNMENT", "सरकारी व्यवस्थित"),
                            ("COMMUNITY", "सामुदायिक"),
                            ("COLLABORATIVE", "कबुलियती"),
                            ("RELIGIOUS", "धार्मिक"),
                            ("PRIVATE", "निजी"),
                            ("LEASEHOLD", "पट्टा"),
                        ],
                        max_length=20,
                        verbose_name="व्यवस्थापन प्रकार",
                    ),
                ),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="क्षेत्रफल (हेक्टेयर)"
                    ),
                ),
                (
                    "canopy_cover_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="वृक्ष ढकावना प्रतिशत",
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(default=False, verbose_name="संरक्षित छ"),
                ),
                (
                    "has_management_plan",
                    models.BooleanField(default=False, verbose_name="व्यवस्थापन योजना छ"),
                ),
                (
                    "last_survey_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="अन्तिम सर्वेक्षण वर्ष"
                    ),
                ),
            ],
            options={
                "verbose_name": "वन क्षेत्र",
                "verbose_name_plural": "वन क्षेत्रहरू",
            },
        ),
        migrations.CreateModel(
            name="ParkGarden",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="पार्क/उद्यानको नाम"),
                ),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="पार्क/उद्यानको नाम (नेपाली)",
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "park_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC_PARK", "सार्वजनिक पार्क"),
                            ("BOTANICAL_GARDEN", "वनस्पति उद्यान"),
                            ("CHILDREN_PARK", "बाल पार्क"),
                            ("COMMUNITY_GARDEN", "सामुदायिक बगैंचा"),
                            ("MEMORIAL_PARK", "स्मारक पार्क"),
                        ],
                        max_length=20,
                        verbose_name="पार्कको प्रकार",
                    ),
                ),
                (
                    "area_square_meters",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="क्षेत्रफल (वर्ग मिटर)",
                    ),
                ),
                (
                    "establishment_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="स्थापना वर्ष"
                    ),
                ),
                (
                    "has_playground",
                    models.BooleanField(default=False, verbose_name="खेलमैदान छ"),
                ),
                (
                    "has_walking_trail",
                    models.BooleanField(default=False, verbose_name="पैदल बाटो छ"),
                ),
                (
                    "has_seating_areas",
                    models.BooleanField(default=False, verbose_name="बस्ने ठाउँ छ"),
                ),
                (
                    "has_water_facility",
                    models.BooleanField(default=False, verbose_name="पानीको सुविधा छ"),
                ),
                (
                    "maintenance_status",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="मर्मतको अवस्था",
                    ),
                ),
            ],
            options={
                "verbose_name": "पार्क तथा उद्यान",
                "verbose_name_plural": "पार्क तथा उद्यानहरू",
            },
        ),
        migrations.CreateModel(
            name="ProtectedArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="संरक्षित क्षेत्रको नाम"),
                ),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="संरक्षित क्षेत्रको नाम (नेपाली)",
                    ),
                ),
                (
                    "ward_numbers",
                    models.CharField(max_length=50, verbose_name="वडा नं.हरू"),
                ),
                (
                    "protection_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL_PARK", "राष्ट्रिय निकुञ्ज"),
                            ("WILDLIFE_RESERVE", "वन्यजन्तु आरक्ष"),
                            ("CONSERVATION_AREA", "संरक्षण क्षेत्र"),
                            ("BUFFER_ZONE", "मध्यवर्ती क्षेत्र"),
                            ("COMMUNITY_FOREST", "सामुदायिक वन"),
                            ("SACRED_GROVE", "धार्मिक वन"),
                            ("WETLAND", "सीमसार क्षेत्र"),
                        ],
                        max_length=30,
                        verbose_name="संरक्षणको प्रकार",
                    ),
                ),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="क्षेत्रफल (हेक्टेयर)"
                    ),
                ),
                (
                    "establishment_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="स्थापना वर्ष"
                    ),
                ),
                (
                    "management_authority",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="व्यवस्थापन निकाय"
                    ),
                ),
                (
                    "conservation_objectives",
                    models.TextField(blank=True, verbose_name="संरक्षण उद्देश्यहरू"),
                ),
                (
                    "has_management_plan",
                    models.BooleanField(default=False, verbose_name="व्यवस्थापन योजना छ"),
                ),
            ],
            options={
                "verbose_name": "संरक्षित क्षेत्र",
                "verbose_name_plural": "संरक्षित क्षेत्रहरू",
            },
        ),
        migrations.CreateModel(
            name="WaterResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="जलस्रोतको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="जलस्रोतको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SPRING", "मुहान"),
                            ("RIVER", "नदी"),
                            ("STREAM", "खोला"),
                            ("LAKE", "ताल"),
                            ("POND", "पोखरी"),
                            ("WELL", "इनार"),
                            ("WETLAND", "सीमसार"),
                        ],
                        max_length=20,
                        verbose_name="स्रोतको प्रकार",
                    ),
                ),
                (
                    "is_perennial",
                    models.BooleanField(default=True, verbose_name="वर्षभरि पानी छ"),
                ),
                (
                    "flow_rate_lps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="प्रवाह दर (लिटर प्रति सेकेन्ड)",
                    ),
                ),
                (
                    "water_quality",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                            ("POLLUTED", "दूषित"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="पानीको गुणस्तर",
                    ),
                ),
                (
                    "is_used_for_drinking",
                    models.BooleanField(
                        default=False, verbose_name="खानेपानीका लागि प्रयोग"
                    ),
                ),
                (
                    "is_used_for_irrigation",
                    models.BooleanField(
                        default=False, verbose_name="सिंचाइका लागि प्रयोग"
                    ),
                ),
                (
                    "households_served",
                    models.PositiveIntegerField(
                        default=0, verbose_name="सेवा पाउने घरपरिवार"
                    ),
                ),
                (
                    "has_conservation_measures",
                    models.BooleanField(default=False, verbose_name="संरक्षण उपायहरू छन्"),
                ),
            ],
            options={
                "verbose_name": "जलस्रोत",
                "verbose_name_plural": "जलस्रोतहरू",
            },
        ),
        migrations.CreateModel(
            name="WatershedArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="जलाधार क्षेत्रको नाम"),
                ),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="जलाधार क्षेत्रको नाम (नेपाली)",
                    ),
                ),
                (
                    "ward_numbers",
                    models.CharField(max_length=50, verbose_name="वडा नं.हरू"),
                ),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="क्षेत्रफल (हेक्टेयर)"
                    ),
                ),
                (
                    "is_main_watershed",
                    models.BooleanField(default=False, verbose_name="मुख्य जलाधार हो"),
                ),
                (
                    "forest_coverage_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="वन क्षेत्र प्रतिशत",
                    ),
                ),
                (
                    "degradation_level",
                    models.CharField(
                        choices=[
                            ("LOW", "कम"),
                            ("MODERATE", "मध्यम"),
                            ("HIGH", "उच्च"),
                            ("SEVERE", "गम्भीर"),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="क्षरण स्तर",
                    ),
                ),
                (
                    "has_conservation_activities",
                    models.BooleanField(
                        default=False, verbose_name="संरक्षण गतिविधिहरू छन्"
                    ),
                ),
            ],
            options={
                "verbose_name": "जलाधार क्षेत्र",
                "verbose_name_plural": "जलाधार क्षेत्रहरू",
            },
        ),
        migrations.CreateModel(
            name="DisasterRiskArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "area_name",
                    models.CharField(max_length=200, verbose_name="क्षेत्रको नाम"),
                ),
                (
                    "area_name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="क्षेत्रको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "disaster_type",
                    models.CharField(
                        choices=[
                            ("EARTHQUAKE", "भूकम्प"),
                            ("LANDSLIDE", "पहिरो"),
                            ("FLOOD", "बाढी"),
                            ("FIRE", "आगलागी"),
                            ("DROUGHT", "खडेरी"),
                            ("HAILSTORM", "असिना"),
                            ("WIND_STORM", "आंधीबतास"),
                            ("LIGHTNING", "चट्याङ"),
                        ],
                        max_length=20,
                        verbose_name="विपद्को प्रकार",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "कम"),
                            ("MODERATE", "मध्यम"),
                            ("HIGH", "उच्च"),
                            ("VERY_HIGH", "अति उच्च"),
                        ],
                        max_length=20,
                        verbose_name="जोखिम स्तर",
                    ),
                ),
                (
                    "vulnerable_households",
                    models.PositiveIntegerField(
                        default=0, verbose_name="जोखिममा रहेका घरपरिवार"
                    ),
                ),
                (
                    "vulnerable_population",
                    models.PositiveIntegerField(
                        default=0, verbose_name="जोखिममा रहेको जनसंख्या"
                    ),
                ),
                (
                    "seasonal_months",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="जोखिमको मौसम"
                    ),
                ),
                (
                    "mitigation_measures",
                    models.TextField(blank=True, verbose_name="न्यूनीकरण उपायहरू"),
                ),
                (
                    "early_warning_system",
                    models.BooleanField(
                        default=False, verbose_name="पूर्व चेतावनी प्रणाली छ"
                    ),
                ),
            ],
            options={
                "verbose_name": "विपद् जोखिम क्षेत्र",
                "verbose_name_plural": "विपद् जोखिम क्षेत्रहरू",
                "unique_together": {("area_name", "ward_number", "disaster_type")},
            },
        ),
        migrations.CreateModel(
            name="ForestProduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("TIMBER", "काठ"),
                            ("FUELWOOD", "दाउरा"),
                            ("BAMBOO", "बाँस"),
                            ("MEDICINAL_PLANTS", "जडिबुटी"),
                            ("NTFP", "गैर काठ वन पैदावार"),
                            ("FODDER", "घाँसपात"),
                            ("FRUITS", "जंगली फलफूल"),
                            ("HONEY", "मह"),
                        ],
                        max_length=30,
                        verbose_name="उत्पादनको प्रकार",
                    ),
                ),
                (
                    "annual_production_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="वार्षिक उत्पादन मात्रा",
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="KG", max_length=20, verbose_name="एकाइ"),
                ),
                (
                    "market_value_npr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="बजार मूल्य (रुपैयाँ)",
                    ),
                ),
                (
                    "harvesting_season",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="संकलन मौसम"
                    ),
                ),
                (
                    "forest_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="environment.forestarea",
                        verbose_name="वन क्षेत्र",
                    ),
                ),
            ],
            options={
                "verbose_name": "वन उत्पादन",
                "verbose_name_plural": "वन उत्पादन",
                "unique_together": {("forest_area", "product_type")},
            },
        ),
    ]
