import { pgTable } from "../../../schema/basic";
import { integer, timestamp, varchar, pgEnum } from "drizzle-orm/pg-core";

// Define country enum
export const foreignEmploymentCountryEnum = pgEnum("foreign_employment_country", [
  "AZERBAIJAN",
  "NIGER",
  "NIGERIA",
  "NICARAGUA",
  "THE_NETHERLANDS",
  "NORWAY",
  "NEPAL",
  "NEW_ZEALAND",
  "PERMISSION",
  "PANAMA",
  "PERU",
  "BOSNIA",
  "PHILIPPINES",
  "PAKISTAN",
  "POLAND",
  "PORTUGAL",
  "PUERTO_RICO",
  "PARAGUAY",
  "QATAR",
  "INTERPOL",
  "ROMANIA",
  "BANGLADESH",
  "RUSSIA",
  "SAUDI_ARABIA",
  "CECILS",
  "SRIDAN",
  "SWEDEN",
  "SINGAPORE",
  "SIERRA_LEONE",
  "SAN_MARINO",
  "SENEGAL",
  "SOMALIA",
  "BELGIUM",
  "SYRIA",
  "FESTIVAL",
  "TOGO",
  "THAILAND",
  "TAJIKISTAN",
  "BITE",
  "TUNISIA",
  "TONGA",
  "EAST_TIMOR",
  "TURKEY",
  "BULGARIA",
  "TAIWAN",
  "TANZANIA",
  "DUNGLAND",
  "UKRAINE",
  "UGANDA",
  "UNITED_NATIONS",
  "UNITED_STATES_OF_AMERICA",
  "URUGUAY",
  "UZBEKISTAN",
  "BAHRAIN",
  "VATICAN_CITY",
  "VENEZUELA",
  "VIETNAM",
  "FLOUR",
  "WELLS",
  "WESTERN_SAMOA",
  "YEMEN",
  "TOKYO",
  "YUGOSLAVIA",
  "SOUTH_AFRICA",
  "BURUNDI",
  "ZAMBIA",
  "ZAIRE",
  "ZIMBABWE",
  "KOSOVO",
  "BRUNEI",
  "BOLIVIA",
  "BRAZIL",
  "UNITED_ARAB_EMIRATES",
  "BAHAMAS",
  "BHUTAN",
  "BOTSWANA",
  "BELARUS",
  "CANADA",
  "CAMBODIA",
  "CONGO",
  "SWITZERLAND",
  "CROATIA",
  "CHILE",
  "AFGHANISTAN",
  "CAMEROON",
  "CHINA",
  "COLOMBIA",
  "COSTA_RICA",
  "CUBA",
  "CYPRUS",
  "CZECHOSLOVAKIA",
  "GERMANY",
  "DUBAI",
  "DENMARK",
  "ALBANIA",
  "DOMINICA",
  "ALGERIA",
  "ECUADOR",
  "EGYPT",
  "SPAIN",
  "ETHIOPIA",
  "FINLAND",
  "FIJI",
  "FAWNS",
  "UNITED_KINGDOM_OF_GREAT_BRITAIN",
  "ARMENIA",
  "GHANA",
  "GAMBIA",
  "GUINEA",
  "GREECE",
  "GUATEMALA",
  "HONG_KONG",
  "THE_AIR",
  "HAITI",
  "HUNGARY",
  "INDONESIA",
  "ANGOLA",
  "REPUBLIC_OF_IRELAND",
  "ISRAEL",
  "INDIA",
  "IRAQ",
  "IRAN",
  "ICELAND",
  "ITALY",
  "JAMAICA",
  "JORDAN",
  "JAPAN",
  "ARGENTINA",
  "KENYA",
  "NORTH_KOREA",
  "SOUTH_KOREA",
  "KATHMANDU",
  "KRVET",
  "KAZAKHSTAN",
  "ARSHATYA",
  "LEBANON",
  "HERZEGOVINA",
  "AUSTRALIA",
  "SRI_LANKA",
  "LIBERIA",
  "LESOTHO",
  "LUXEMBOURG",
  "LEON",
  "LIBYA",
  "MOROCCO",
  "MONACO",
  "MADAGASCAR",
  "THE_GARDENER",
  "ARUBA",
  "MYANMAR",
  "MONGOLIA",
  "MACAU",
  "MALTA",
  "MAURITIUS",
  "MALDIVES",
  "MEXICO",
  "MALAYSIA",
  "MOZAMBIQUE",
  "NAMIBIA"
]);

export const wardWiseForeignEmploymentCountries = pgTable("ward_wise_foreign_employment_countries", {
  id: varchar("id", { length: 36 }).primaryKey(),

  // Ward reference
  wardNumber: integer("ward_number").notNull(),

  // Country of employment
  country: foreignEmploymentCountryEnum("country").notNull(),

  // Population count in that country
  population: integer("population").notNull(),

  // Metadata
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date()),
  createdAt: timestamp("created_at").defaultNow(),
});

export type WardWiseForeignEmploymentCountries = typeof wardWiseForeignEmploymentCountries.$inferSelect;
export type NewWardWiseForeignEmploymentCountries = typeof wardWiseForeignEmploymentCountries.$inferInsert;
