# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MunicipalityWideAgriculturalExperts",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="कर्मचारीको नाम"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("OFFICER_SIXTH", "अधिकृत छैटौ (शाखा प्रमुख)"),
                            ("TECHNICAL_ASSISTANT_FIFTH", "प्रा.स (सहायक पाँचौ)"),
                            ("TECHNICAL_ASSISTANT_FOURTH", "ना.प्रा.स (सहायक चौथो)"),
                            (
                                "TECHNICAL_ASSISTANT_PROVINCE_FOURTH",
                                "ना.प्रा.स (प्रदेश) (सहायक चौथो)",
                            ),
                        ],
                        max_length=40,
                        verbose_name="पद",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="सम्पर्क न."),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी कृषि विज्ञ",
                "verbose_name_plural": "गाउँपालिका व्यापी कृषि विज्ञ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideAgricultureRelatedFarmersGroup",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="नाम")),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी कृषि सम्बन्धी किसान समूह",
                "verbose_name_plural": "गाउँपालिका व्यापी कृषि सम्बन्धी किसान समूह",
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideCommercialAgriculturalAnimalHusbandryFarmersGroup",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="नाम")),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VEGETABLE_FARMING", "तरकारी खेती"),
                            ("GOAT_FARMING", "बाख्रा पालन"),
                            ("POULTRY_FARMING", "कुखुरा पालन"),
                            ("FISH_FARMING", "माछा पालन"),
                            ("CATTLE_FARMING", "गाई पालन"),
                            ("ANIMAL_HUSBANDRY", "पशुपालन"),
                            ("LIVESTOCK_POULTRY", "पशुपन्छी पालन"),
                            ("BEEKEEPING", "मौरी पालन"),
                            ("FRUIT_FARMING", "फलफूल खेती"),
                            ("MUSHROOM_FARMING", "च्याउ खेती"),
                            ("PIG_FARMING", "सुंगुर पालन"),
                            ("NURSERY", "नर्सरी"),
                            ("DAIRY_FARMING", "दुग्ध उत्पादन"),
                            ("MIXED_FARMING", "मिश्रित खेती"),
                            ("AGRICULTURE", "कृषि"),
                            ("ORGANIC_FARMING", "जैविक खेती"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=30,
                        verbose_name="व्यापारको प्रकार",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी व्यापारिक कृषि पशुपालन किसान समूह",
                "verbose_name_plural": "गाउँपालिका व्यापी व्यापारिक कृषि पशुपालन किसान समूह",
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideCooperatives",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="नाम")),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "cooperative_type",
                    models.CharField(
                        choices=[
                            ("AGRICULTURE", "कृषि"),
                            ("MULTIPURPOSE", "बहुउद्देश्यीय"),
                            ("WOMEN", "महिला"),
                            ("SOCIAL_ENTREPRENEURSHIP", "सामाजिक उद्यमी"),
                            ("OTHER", "अन्य"),
                        ],
                        default="AGRICULTURE",
                        max_length=30,
                        verbose_name="सहकारी प्रकार",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी सहकारी",
                "verbose_name_plural": "गाउँपालिका व्यापी सहकारीहरू",
                "ordering": ["ward_number", "name"],
            },
        ),
        migrations.CreateModel(
            name="TouristicSite",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="नाम")),
                (
                    "significance_type",
                    models.CharField(
                        choices=[
                            ("TOURISTIC_RELIGIOUS", "पर्यटकीय तथा धार्मिक"),
                            (
                                "TOURISTIC_RELIGIOUS_SCENIC",
                                "पर्यटकीय तथा धार्मिक, दृश्यावलोकन",
                            ),
                            ("TOURISTIC", "पर्यटकीय"),
                            ("RELIGIOUS", "धार्मिक"),
                            ("SCENIC", "दृश्यावलोकन"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=30,
                        verbose_name="महत्त्व प्रकार",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="विवरण"),
                ),
            ],
            options={
                "verbose_name": "पर्यटकीय स्थल",
                "verbose_name_plural": "पर्यटकीय स्थलहरू",
                "ordering": ["ward_number", "name"],
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideAnimalDiseases",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal_type",
                    models.CharField(max_length=100, verbose_name="पशु प्रकार"),
                ),
                ("major_diseases", models.TextField(verbose_name="प्रमुख रोगहरू")),
                ("major_pests", models.TextField(verbose_name="प्रमुख परजीवीहरू")),
                (
                    "preventive_measures",
                    models.TextField(
                        blank=True, null=True, verbose_name="रोकथामका उपायहरू"
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी पशु रोग",
                "verbose_name_plural": "गाउँपालिका व्यापी पशु रोगहरू",
                "unique_together": {("animal_type",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideAnimalProducts",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal_product_type",
                    models.CharField(
                        choices=[
                            ("MILK", "दूध"),
                            ("MILK_PRODUCT", "दुग्ध उत्पादन"),
                            ("EGG", "अण्डा"),
                            ("MEAT", "मासु"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="पशु उत्पादनको प्रकार",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        choices=[
                            ("TON", "टन"),
                            ("KG", "केजी"),
                            ("COUNT", "संख्या"),
                            ("LITER", "लिटर"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=10,
                        verbose_name="मापदण्डको एकाइ",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="मात्रा",
                    ),
                ),
                (
                    "value_in_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="मूल्य (रु.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी पशु उत्पादन",
                "verbose_name_plural": "गाउँपालिका व्यापी पशु उत्पादन",
                "unique_together": {("animal_product_type", "measurement_unit")},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideCropDiseases",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.CharField(
                        choices=[
                            ("RICE", "धान"),
                            ("WHEAT", "गहुँ"),
                            ("CORN", "मकै"),
                            ("VEGETABLES", "तरकारी"),
                            ("FRUITS", "फलफूल"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="बाली",
                    ),
                ),
                ("major_pests", models.TextField(verbose_name="प्रमुख शत्रु जीव")),
                ("major_diseases", models.TextField(verbose_name="प्रमुख रोग")),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी बालीको रोग",
                "verbose_name_plural": "गाउँपालिका व्यापी बालीको रोग",
                "unique_together": {("crop",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideFoodCrops",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food_crop",
                    models.CharField(
                        choices=[
                            ("PADDY", "धान"),
                            ("CORN", "मकै"),
                            ("WHEAT", "गहुँ"),
                            ("MILLET", "कोदो"),
                            ("BARLEY", "जौ"),
                            ("PHAPAR", "फापर"),
                            ("JUNELO", "जुनेलो"),
                            ("KAGUNO", "कागुनो"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="खाद्यान्न बाली",
                    ),
                ),
                (
                    "production_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="उत्पादन (टन)",
                    ),
                ),
                (
                    "sales_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="बिक्री (टन)",
                    ),
                ),
                (
                    "revenue_in_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="आम्दानी (रु.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी खाद्यान्न बाली",
                "verbose_name_plural": "गाउँपालिका व्यापी खाद्यान्न बाली",
                "unique_together": {("food_crop",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideForeignEmploymentCountries",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=100, verbose_name="देश")),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वैदेशिक रोजगार देश",
                "verbose_name_plural": "वैदेशिक रोजगार देश",
                "unique_together": {("country",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideFruits",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fruit_type",
                    models.CharField(
                        choices=[
                            ("MANGO", "आँप"),
                            ("JACKFRUIT", "रुख कटहर"),
                            ("LITCHI", "लीची"),
                            ("BANANA", "केरा"),
                            ("LEMON", "कागती"),
                            ("ORANGE", "सुन्तला"),
                            ("NIBUWA", "निबुवा"),
                            ("SWEET_ORANGE", "मिठो सुन्तला"),
                            ("SWEET_LEMON", "मिठो कागती"),
                            ("JYAMIR", "ज्यामिर"),
                            ("POMELO", "भोगटे"),
                            ("PINEAPPLE", "भुइंकटहर"),
                            ("PAPAYA", "मेवा"),
                            ("AVOCADO", "घिउ"),
                            ("KIWI", "किवी"),
                            ("GUAVA", "अम्बा"),
                            ("PLUM", "आलुबुखारा"),
                            ("PEACH", "आरु"),
                            ("PEAR", "नाशपाती"),
                            ("POMEGRANATE", "दाडिम"),
                            ("WALNUT", "ओखर"),
                            ("JAPANESE_PERSIMMON", "हरियो खुर्पानी"),
                            ("HOG_PLUM", "लापसी"),
                            ("NONE", "छैन"),
                        ],
                        max_length=25,
                        verbose_name="फलफूलको प्रकार",
                    ),
                ),
                (
                    "production_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="उत्पादन (टन)",
                    ),
                ),
                (
                    "sales_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="बिक्री (टन)",
                    ),
                ),
                (
                    "revenue_in_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="आम्दानी (रु.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी फलफूल",
                "verbose_name_plural": "गाउँपालिका व्यापी फलफूल",
                "unique_together": {("fruit_type",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideIrrigationSource",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "irrigation_source",
                    models.CharField(
                        choices=[
                            ("LAKE_OR_RESERVOIR", "ताल वा जलाशय"),
                            ("IRRIGATION_CANAL", "सिंचाई नहर"),
                            ("RAINWATER_COLLECTION", "वर्षाको पानी संकलन"),
                            ("ELECTRIC_LIFT_IRRIGATION", "विद्युतीय लिफ्ट सिंचाई"),
                            ("CANAL", "नहर"),
                            ("PUMPING_SET", "पम्पिङ सेट"),
                            ("UNDERGROUND_IRRIGATION", "भूमिगत सिंचाई"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=30,
                        verbose_name="सिंचाइको स्रोत",
                    ),
                ),
                (
                    "coverage_in_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="क्षेत्रफल (हेक्टर)",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी सिंचाइ स्रोत",
                "verbose_name_plural": "गाउँपालिका व्यापी सिंचाइ स्रोत",
                "unique_together": {("irrigation_source",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideOilSeeds",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oil_seed",
                    models.CharField(
                        choices=[
                            ("MUSTARD", "तोरी/सरसोँ"),
                            ("FLAX", "तिसी"),
                            ("SUNFLOWER", "सूर्यमुखी"),
                            ("OTHER", "अन्य"),
                            ("NONE", "छैन"),
                        ],
                        max_length=20,
                        verbose_name="तेलहन बाली",
                    ),
                ),
                (
                    "production_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="उत्पादन (टन)",
                    ),
                ),
                (
                    "sales_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="बिक्री (टन)",
                    ),
                ),
                (
                    "revenue_in_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="आम्दानी (रु.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी तेलहन बाली",
                "verbose_name_plural": "गाउँपालिका व्यापी तेलहन बाली",
                "unique_together": {("oil_seed",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWidePulses",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pulse",
                    models.CharField(
                        choices=[
                            ("LENTIL", "मसुरो"),
                            ("CHICKPEA", "चना"),
                            ("PEA", "केराउ"),
                            ("PIGEON_PEA", "रहर"),
                            ("BLACK_GRAM", "मास"),
                            ("SOYABEAN", "भटमास"),
                            ("SNAKE_BEAN", "बोडी"),
                            ("BEAN", "सिमी"),
                            ("HORSE_GRAM", "गहत"),
                            ("OTHER", "अन्य"),
                            ("NONE", "छैन"),
                        ],
                        max_length=20,
                        verbose_name="दलहन बाली",
                    ),
                ),
                (
                    "production_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="उत्पादन (टन)",
                    ),
                ),
                (
                    "sales_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="बिक्री (टन)",
                    ),
                ),
                (
                    "revenue_in_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="आम्दानी (रु.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी दलहन बाली",
                "verbose_name_plural": "गाउँपालिका व्यापी दलहन बाली",
                "unique_together": {("pulse",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideSpices",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "spice_type",
                    models.CharField(
                        choices=[
                            ("GARLIC", "लसुन"),
                            ("TURMERIC", "बेसार"),
                            ("CHILI_PEPPER", "खुर्सानी"),
                            ("GINGER", "अदुवा"),
                            ("CORIANDER", "धनिया"),
                            ("SICHUAN_PEPPER", "टिमुर"),
                            ("BLACK_PEPPER", "मरिच"),
                            ("CINNAMOMUM_TAMALA", "तेजपात"),
                            ("CUMIN", "जीरा"),
                            ("FENUGREEK", "मेथी"),
                            ("OTHER", "अन्य"),
                            ("NONE", "छैन"),
                        ],
                        max_length=25,
                        verbose_name="मसलाको प्रकार",
                    ),
                ),
                (
                    "production_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="उत्पादन (टन)",
                    ),
                ),
                (
                    "sales_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="बिक्री (टन)",
                    ),
                ),
                (
                    "revenue_in_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="आम्दानी (रु.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी मसला",
                "verbose_name_plural": "गाउँपालिका व्यापी मसला",
                "unique_together": {("spice_type",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideVegetables",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vegetable_type",
                    models.CharField(
                        choices=[
                            ("POTATO", "आलु"),
                            ("CAULIFLOWER", "काउली"),
                            ("CABBAGE", "बन्दाकोपी"),
                            ("TOMATO", "गोलभेडा"),
                            ("RADISH", "मुला"),
                            ("CARROT", "गाजर"),
                            ("TURNIP", "सल्गम"),
                            ("CAPSICUM", "भेडेखुर्सानी"),
                            ("OKRA", "भिन्डी"),
                            ("BRINJAL", "भन्टा"),
                            ("ONION", "प्याज"),
                            ("STRING_BEAN", "सिमी"),
                            ("RED_KIDNEY_BEAN", "राजमा"),
                            ("CUCUMBER", "काकरो"),
                            ("PUMPKIN", "फर्सी"),
                            ("BITTER_GOURD", "करेला"),
                            ("LUFFA", "घिरौला"),
                            ("SNAKE_GOURD", "चिचिण्डो"),
                            ("CALABASH", "लौका"),
                            ("BALSAM_APPLE", "तिते करेला"),
                            ("MUSHROOM", "च्याउ"),
                            ("SQUICE", "इस्कुस"),
                            ("MUSTARD_GREENS", "रायो साग"),
                            ("GARDEN_CRESS", "चमसुर"),
                            ("SPINACH", "पालुङ्गो"),
                            ("COLOCASIA", "तारो"),
                            ("YAM", "बन तारो"),
                            ("OTHER", "अन्य"),
                            ("NONE", "छैन"),
                        ],
                        max_length=25,
                        verbose_name="तरकारीको प्रकार",
                    ),
                ),
                (
                    "production_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="उत्पादन (टन)",
                    ),
                ),
                (
                    "sales_in_tonnes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="बिक्री (टन)",
                    ),
                ),
                (
                    "revenue_in_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="आम्दानी (रु.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी तरकारी",
                "verbose_name_plural": "गाउँपालिका व्यापी तरकारी",
                "unique_together": {("vegetable_type",)},
            },
        ),
        migrations.CreateModel(
            name="MunicipalityWideVegetablesAndFruitsDiseases",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.CharField(
                        choices=[
                            ("TOMATO", "गोलभेडा"),
                            ("CAULIFLOWER", "काउली"),
                            ("CABBAGE", "बन्दाकोपी"),
                            ("POTATO", "आलु"),
                            ("MUSTARD", "तोरी"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="बाली",
                    ),
                ),
                ("major_pests", models.TextField(verbose_name="प्रमुख शत्रु जीव")),
                ("major_diseases", models.TextField(verbose_name="प्रमुख रोग")),
            ],
            options={
                "verbose_name": "गाउँपालिका व्यापी तरकारी र फलफूलको रोग",
                "verbose_name_plural": "गाउँपालिका व्यापी तरकारी र फलफूलको रोग",
                "unique_together": {("crop",)},
            },
        ),
        migrations.CreateModel(
            name="WardAgeGenderWiseEconomicallyActivePopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("AGE_0_TO_14", "०-१४ वर्ष"),
                            ("AGE_15_TO_59", "१५-५९ वर्ष"),
                            ("AGE_60_PLUS", "६० वर्षभन्दा माथि"),
                        ],
                        max_length=20,
                        verbose_name="उमेर समूह",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "पुरुष"),
                            ("FEMALE", "महिला"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=10,
                        verbose_name="लिंग",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत उमेर लिंग अनुसार आर्थिक रूपमा सक्रिय जनसंख्या",
                "verbose_name_plural": "वडागत उमेर लिंग अनुसार आर्थिक रूपमा सक्रिय जनसंख्या",
                "unique_together": {("ward_number", "age_group", "gender")},
            },
        ),
        migrations.CreateModel(
            name="WardTimeWiseHouseholdChores",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "time_spent",
                    models.CharField(
                        choices=[
                            ("LESS_THAN_1_HOUR", "१ घण्टाभन्दा कम"),
                            ("HOURS_1_TO_3", "१-३ घण्टा"),
                            ("HOURS_4_TO_6", "४-६ घण्टा"),
                            ("HOURS_7_TO_9", "७-९ घण्टा"),
                            ("HOURS_10_TO_12", "१०-१२ घण्टा"),
                            ("MORE_THAN_12_HOURS", "१२ घण्टाभन्दा बढी"),
                        ],
                        max_length=20,
                        verbose_name="समय व्यतीत",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत समय अनुसार घरेलु काम",
                "verbose_name_plural": "वडागत समय अनुसार घरेलु काम",
                "unique_together": {("ward_number", "time_spent")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseAnnualAgriculturalSustenance",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "months_sustained",
                    models.CharField(
                        choices=[
                            ("UPTO_THREE_MONTHS", "३ महिना सम्म"),
                            ("THREE_TO_SIX_MONTHS", "३ देखि ६ महिना"),
                            ("SIX_TO_NINE_MONTHS", "६ देखि ९ महिना"),
                            ("TWELVE_MONTHS", "१२ महिना"),
                        ],
                        max_length=25,
                        verbose_name="चल्ने महिना",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत वार्षिक कृषि उत्पादनको निर्वाह",
                "verbose_name_plural": "वडागत वार्षिक कृषि उत्पादनको निर्वाह",
                "unique_together": {("ward_number", "months_sustained")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseFinancialAccounts",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "financial_account_type",
                    models.CharField(
                        choices=[
                            ("BANK_ACCOUNT", "बैंक खाता"),
                            ("COOPERATIVE_ACCOUNT", "सहकारी खाता"),
                            ("MICROFINANCE_ACCOUNT", "लघुवित्त खाता"),
                            ("MOBILE_BANKING", "मोबाइल बैंकिङ"),
                            ("DIGITAL_WALLET", "डिजिटल वालेट"),
                            ("NO_ACCOUNT", "कुनै खाता छैन"),
                        ],
                        max_length=20,
                        verbose_name="वित्तीय खाताको प्रकार",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत वित्तीय खाता",
                "verbose_name_plural": "वडागत वित्तीय खाता",
                "unique_together": {("ward_number", "financial_account_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseForeignEmploymentCountries",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="देश")),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत वैदेशिक रोजगार देश",
                "verbose_name_plural": "वडागत वैदेशिक रोजगार देश",
                "unique_together": {("ward_number", "country")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseholdBase",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "base_type",
                    models.CharField(
                        choices=[
                            ("CONCRETE_PILLAR", "कंक्रिट स्तम्भ"),
                            ("CEMENT_JOINED", "सिमेन्ट जोडिएको"),
                            ("MUD_JOINED", "माटो जोडिएको"),
                            ("WOOD_POLE", "काठको खाम्बा"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="घरको जगको प्रकार",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत घरको जग",
                "verbose_name_plural": "वडागत घरको जग",
                "unique_together": {("ward_number", "base_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseholdIncomeSource",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "income_source",
                    models.CharField(
                        choices=[
                            ("JOB", "जागिर"),
                            ("AGRICULTURE", "कृषि"),
                            ("BUSINESS", "व्यापार"),
                            ("INDUSTRY", "उद्योग"),
                            ("FOREIGN_EMPLOYMENT", "वैदेशिक रोजगार"),
                            ("LABOUR", "श्रम"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="आम्दानीको स्रोत",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत घरपरिवारको आम्दानीको स्रोत",
                "verbose_name_plural": "वडागत घरपरिवारको आम्दानीको स्रोत",
                "unique_together": {("ward_number", "income_source")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseholdLandPossessions",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत घरपरिवारको जमिनको स्वामित्व",
                "verbose_name_plural": "वडागत घरपरिवारको जमिनको स्वामित्व",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseholdOuterWall",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "wall_type",
                    models.CharField(
                        choices=[
                            ("CEMENT_JOINED", "सिमेन्ट जोडिएको"),
                            ("UNBAKED_BRICK", "काच्ची इँट"),
                            ("MUD_JOINED", "माटो जोडिएको"),
                            ("TIN", "पाता"),
                            ("BAMBOO", "बाँस"),
                            ("WOOD", "काठ"),
                            ("PREFAB", "प्रिफ्याब"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="बाहिरी भित्ताको प्रकार",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत घरको बाहिरी भित्ता",
                "verbose_name_plural": "वडागत घरको बाहिरी भित्ता",
                "unique_together": {("ward_number", "wall_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseholdsInAgriculture",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "involved_in_agriculture",
                    models.PositiveIntegerField(
                        default=0, verbose_name="कृषिमा संलग्न घरपरिवार"
                    ),
                ),
                (
                    "non_involved_in_agriculture",
                    models.PositiveIntegerField(
                        default=0, verbose_name="कृषिमा संलग्न नभएका घरपरिवार"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत कृषिमा संलग्न घरपरिवार",
                "verbose_name_plural": "वडागत कृषिमा संलग्न घरपरिवार",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseholdsLoanUse",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "loan_use",
                    models.CharField(
                        choices=[
                            ("AGRICULTURE", "कृषि"),
                            ("BUSINESS", "व्यापार"),
                            ("HOUSEHOLD_EXPENSES", "घरेलु खर्च"),
                            ("FOREIGN_EMPLOYMENT", "वैदेशिक रोजगार"),
                            ("EDUCATION", "शिक्षा"),
                            ("HEALTH_TREATMENT", "स्वास्थ्य उपचार"),
                            ("HOME_CONSTRUCTION", "घर निर्माण"),
                            ("VEHICLE_PURCHASE", "सवारीसाधन खरिद"),
                            ("CEREMONY", "समारोह"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=25,
                        verbose_name="ऋणको प्रयोग",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत घरपरिवारको ऋणको प्रयोग",
                "verbose_name_plural": "वडागत घरपरिवारको ऋणको प्रयोग",
                "unique_together": {("ward_number", "loan_use")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseholdsOnLoan",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत ऋणमा रहेका घरपरिवार",
                "verbose_name_plural": "वडागत ऋणमा रहेका घरपरिवार",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHouseOwnership",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "निजी"),
                            ("RENT", "भाडा"),
                            ("INSTITUTIONAL", "संस्थागत"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="स्वामित्वको प्रकार",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत घर स्वामित्व",
                "verbose_name_plural": "वडागत घर स्वामित्व",
                "unique_together": {("ward_number", "ownership_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseIrrigatedArea",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "irrigated_area_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="सिंचित क्षेत्रफल (हेक्टर)",
                    ),
                ),
                (
                    "unirrigated_area_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="असिंचित क्षेत्रफल (हेक्टर)",
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत सिंचित क्षेत्रफल",
                "verbose_name_plural": "वडागत सिंचित क्षेत्रफल",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseLandOwnership",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "land_ownership_type",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "निजी"),
                            ("GUTHI", "गुठी"),
                            ("PUBLIC_EILANI", "सार्वजनिक ऐलानी"),
                            ("VILLAGE_BLOCK", "गाउँ ब्लक"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="जमिन स्वामित्वको प्रकार",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत जमिन स्वामित्व",
                "verbose_name_plural": "वडागत जमिन स्वामित्व",
                "unique_together": {("ward_number", "land_ownership_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseMajorSkills",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("AGRICULTURE_RELATED", "कृषि सम्बन्धी"),
                            ("LIVESTOCK_RELATED", "पशुपालन सम्बन्धी"),
                            ("CONSTRUCTION_RELATED", "निर्माण सम्बन्धी"),
                            ("HANDICRAFT_RELATED", "हस्तकला सम्बन्धी"),
                            ("MECHANICAL_RELATED", "मेकानिकल सम्बन्धी"),
                            ("ELECTRICAL_RELATED", "विद्युत सम्बन्धी"),
                            ("PLUMBING_RELATED", "प्लम्बिङ सम्बन्धी"),
                            ("TAILORING_RELATED", "सिलाई सम्बन्धी"),
                            ("BEAUTY_PARLOR", "सौन्दर्य पार्लर"),
                            ("DRIVING_RELATED", "चालक सम्बन्धी"),
                            ("COMPUTER_RELATED", "कम्प्युटर सम्बन्धी"),
                            ("HEALTH_RELATED", "स्वास्थ्य सम्बन्धी"),
                            ("TEACHING_RELATED", "शिक्षण सम्बन्धी"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=40,
                        verbose_name="सीपको प्रकार",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत प्रमुख सीप",
                "verbose_name_plural": "वडागत प्रमुख सीप",
                "unique_together": {("ward_number", "skill_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseRemittance",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "amount_group",
                    models.CharField(
                        choices=[
                            ("RS_0_TO_49999", "० देखि ४९,९९९ रुपैयाँ"),
                            ("RS_50000_TO_99999", "५०,००० देखि ९९,९९९ रुपैयाँ"),
                            ("RS_100000_TO_149999", "१,००,००० देखि १,४९,९९९ रुपैयाँ"),
                            ("RS_150000_TO_199999", "१,५०,००० देखि १,९९,९९९ रुपैयाँ"),
                            ("RS_200000_TO_249999", "२,००,००० देखि २,४९,९९९ रुपैयाँ"),
                            ("RS_250000_TO_299999", "२,५०,००० देखि २,९९,९९९ रुपैयाँ"),
                            ("RS_300000_TO_349999", "३,००,००० देखि ३,४९,९९९ रुपैयाँ"),
                            ("RS_350000_TO_399999", "३,५०,००० देखि ३,९९,९९९ रुपैयाँ"),
                            ("RS_400000_TO_449999", "४,००,००० देखि ४,४९,९९९ रुपैयाँ"),
                            ("RS_450000_TO_499999", "४,५०,००० देखि ४,९९,९९९ रुपैयाँ"),
                            ("RS_500000_PLUS", "५,००,००० रुपैयाँभन्दा माथि"),
                        ],
                        max_length=25,
                        verbose_name="रकम समूह",
                    ),
                ),
                (
                    "sending_population",
                    models.PositiveIntegerField(default=0, verbose_name="पठाउने जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत रेमिटेन्स",
                "verbose_name_plural": "वडागत रेमिटेन्स",
                "unique_together": {("ward_number", "amount_group")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseRemittanceExpenses",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "remittance_expense",
                    models.CharField(
                        choices=[
                            ("education", "शिक्षा"),
                            ("health", "स्वास्थ्य"),
                            ("household_use", "घरेलु प्रयोग"),
                            ("festivals", "चाडपर्व"),
                            ("loan_payment", "ऋण भुक्तानी"),
                            ("loaned_others", "अरुलाई ऋण"),
                            ("saving", "बचत"),
                            ("house_construction", "घर निर्माण"),
                            ("land_ownership", "जमिन स्वामित्व"),
                            ("jwellery_purchase", "गहना खरिद"),
                            ("goods_purchase", "सामान खरिद"),
                            ("business_investment", "व्यापारिक लगानी"),
                            ("other", "अन्य"),
                            ("unknown", "थाहा छैन"),
                        ],
                        max_length=25,
                        verbose_name="रेमिटेन्स खर्च",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत रेमिटेन्स खर्च",
                "verbose_name_plural": "वडागत रेमिटेन्स खर्च",
                "unique_together": {("ward_number", "remittance_expense")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseTimeToFinancialOrganization",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "time_to_financial_organization_type",
                    models.CharField(
                        choices=[
                            ("UNDER_15_MIN", "१५ मिनेट भन्दा कम"),
                            ("UNDER_30_MIN", "१५-३० मिनेट"),
                            ("UNDER_1_HOUR", "३०-६० मिनेट"),
                            ("1_HOUR_OR_MORE", "१ घण्टा वा बढी"),
                            ("LABOR", "श्रमिक"),
                            ("WOMEN", "महिला"),
                            ("YOUTH", "युवा"),
                        ],
                        max_length=20,
                        verbose_name="वित्तीय संस्थासम्म पुग्ने समय",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत वित्तीय संस्थासम्म पुग्ने समय",
                "verbose_name_plural": "वडागत वित्तीय संस्थासम्म पुग्ने समय",
                "unique_together": {
                    ("ward_number", "time_to_financial_organization_type")
                },
            },
        ),
        migrations.CreateModel(
            name="WardWiseTrainedPopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "trained_population",
                    models.PositiveIntegerField(
                        default=0, verbose_name="तालिम प्राप्त जनसंख्या"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत तालिम प्राप्त जनसंख्या",
                "verbose_name_plural": "वडागत तालिम प्राप्त जनसंख्या",
                "unique_together": {("ward_number",)},
            },
        ),
    ]
