import { z } from "zod";

// Define the foreign employment country enum to match the database enum
export const ForeignEmploymentCountryEnum = z.enum([
  "AZERBAIJAN",
  "NIGER",
  "NIGERIA",
  "NICARAGUA",
  "THE_NETHERLANDS",
  "NORWAY",
  "NEPAL",
  "NEW_ZEALAND",
  "PERMISSION",
  "PANAMA",
  "PERU",
  "BOSNIA",
  "PHILIPPINES",
  "PAKISTAN",
  "POLAND",
  "PORTUGAL",
  "PUERTO_RICO",
  "PARAGUAY",
  "QATAR",
  "INTERPOL",
  "ROMANIA",
  "BANGLADESH",
  "RUSSIA",
  "SAUDI_ARABIA",
  "CECILS",
  "SRIDAN",
  "SWEDEN",
  "SINGAPORE",
  "SIERRA_LEONE",
  "SAN_MARINO",
  "SENEGAL",
  "SOMALIA",
  "BELGIUM",
  "SYRIA",
  "FESTIVAL",
  "TOGO",
  "THAILAND",
  "TAJIKISTAN",
  "BITE",
  "TUNISIA",
  "TONGA",
  "EAST_TIMOR",
  "TURKEY",
  "BULGARIA",
  "TAIWAN",
  "TANZANIA",
  "DUNGLAND",
  "UKRAINE",
  "UGANDA",
  "UNITED_NATIONS",
  "UNITED_STATES_OF_AMERICA",
  "URUGUAY",
  "UZBEKISTAN",
  "BAHRAIN",
  "VATICAN_CITY",
  "VENEZUELA",
  "VIETNAM",
  "FLOUR",
  "WELLS",
  "WESTERN_SAMOA",
  "YEMEN",
  "TOKYO",
  "YUGOSLAVIA",
  "SOUTH_AFRICA",
  "BURUNDI",
  "ZAMBIA",
  "ZAIRE",
  "ZIMBABWE",
  "KOSOVO",
  "BRUNEI",
  "BOLIVIA",
  "BRAZIL",
  "UNITED_ARAB_EMIRATES",
  "BAHAMAS",
  "BHUTAN",
  "BOTSWANA",
  "BELARUS",
  "CANADA",
  "CAMBODIA",
  "CONGO",
  "SWITZERLAND",
  "CROATIA",
  "CHILE",
  "AFGHANISTAN",
  "CAMEROON",
  "CHINA",
  "COLOMBIA",
  "COSTA_RICA",
  "CUBA",
  "CYPRUS",
  "CZECHOSLOVAKIA",
  "GERMANY",
  "DUBAI",
  "DENMARK",
  "ALBANIA",
  "DOMINICA",
  "ALGERIA",
  "ECUADOR",
  "EGYPT",
  "SPAIN",
  "ETHIOPIA",
  "FINLAND",
  "FIJI",
  "FAWNS",
  "UNITED_KINGDOM_OF_GREAT_BRITAIN",
  "ARMENIA",
  "GHANA",
  "GAMBIA",
  "GUINEA",
  "GREECE",
  "GUATEMALA",
  "HONG_KONG",
  "THE_AIR",
  "HAITI",
  "HUNGARY",
  "INDONESIA",
  "ANGOLA",
  "REPUBLIC_OF_IRELAND",
  "ISRAEL",
  "INDIA",
  "IRAQ",
  "IRAN",
  "ICELAND",
  "ITALY",
  "JAMAICA",
  "JORDAN",
  "JAPAN",
  "ARGENTINA",
  "KENYA",
  "NORTH_KOREA",
  "SOUTH_KOREA",
  "KATHMANDU",
  "KRVET",
  "KAZAKHSTAN",
  "ARSHATYA",
  "LEBANON",
  "HERZEGOVINA",
  "AUSTRALIA",
  "SRI_LANKA",
  "LIBERIA",
  "LESOTHO",
  "LUXEMBOURG",
  "LEON",
  "LIBYA",
  "MOROCCO",
  "MONACO",
  "MADAGASCAR",
  "THE_GARDENER",
  "ARUBA",
  "MYANMAR",
  "MONGOLIA",
  "MACAU",
  "MALTA",
  "MAURITIUS",
  "MALDIVES",
  "MEXICO",
  "MALAYSIA",
  "MOZAMBIQUE",
  "NAMIBIA",
]);
export type ForeignEmploymentCountryType = z.infer<typeof ForeignEmploymentCountryEnum>;

// Schema for ward-wise foreign employment countries data
export const wardWiseForeignEmploymentCountriesSchema = z.object({
  id: z.string().optional(),
  wardNumber: z.number().int().positive(),
  country: ForeignEmploymentCountryEnum,
  population: z.number().int().nonnegative(),
});

// Schema for filtering ward-wise foreign employment countries data
export const wardWiseForeignEmploymentCountriesFilterSchema = z.object({
  wardNumber: z.number().int().positive().optional(),
  country: ForeignEmploymentCountryEnum.optional(),
});

export const updateWardWiseForeignEmploymentCountriesSchema = wardWiseForeignEmploymentCountriesSchema;

export type WardWiseForeignEmploymentCountriesData = z.infer<
  typeof wardWiseForeignEmploymentCountriesSchema
>;
export type UpdateWardWiseForeignEmploymentCountriesData = WardWiseForeignEmploymentCountriesData;
export type WardWiseForeignEmploymentCountriesFilter = z.infer<
  typeof wardWiseForeignEmploymentCountriesFilterSchema
>;

// Export the country options for use in UI components
export const foreignEmploymentCountryOptions = [
  { value: "AZERBAIJAN", label: "अजरबैजान" },
  { value: "NIGER", label: "नाइजर" },
  { value: "NIGERIA", label: "नाइजेरिया" },
  { value: "NICARAGUA", label: "निकारागुवा" },
  { value: "THE_NETHERLANDS", label: "नेदरल्याण्ड" },
  { value: "NORWAY", label: "नर्वे" },
  { value: "NEPAL", label: "नेपाल" },
  { value: "NEW_ZEALAND", label: "न्यूजिल्याण्ड" },
  { value: "PERMISSION", label: "अनुमोज" },
  { value: "PANAMA", label: "पनामा" },
  { value: "PERU", label: "पेरु" },
  { value: "BOSNIA", label: "बोस्निया" },
  { value: "PHILIPPINES", label: "फिलिपिन्स" },
  { value: "PAKISTAN", label: "पाकिस्तान" },
  { value: "POLAND", label: "पोल्याण्ड" },
  { value: "PORTUGAL", label: "पोर्चुगल" },
  { value: "PUERTO_RICO", label: "पोर्टोरिको" },
  { value: "PARAGUAY", label: "पाराग्वै" },
  { value: "QATAR", label: "कतार" },
  { value: "INTERPOL", label: "इन्टरपोल" },
  { value: "ROMANIA", label: "रोमानिया" },
  { value: "BANGLADESH", label: "बंगलादेश" },
  { value: "RUSSIA", label: "रुस" },
  { value: "SAUDI_ARABIA", label: "साउदी अरेबिया" },
  { value: "OTHER", label: "अन्य" },
  { value: "CECILS", label: "सेसेल्स" },
  { value: "SRIDAN", label: "सृडान" },
  { value: "SWEDEN", label: "स्वीडेन" },
  { value: "SINGAPORE", label: "सिंगापुर" },
  { value: "SIERRA_LEONE", label: "सियरा लियोन" },
  { value: "SAN_MARINO", label: "सानमारिनो" },
  { value: "SENEGAL", label: "सेनेगल" },
  { value: "SOMALIA", label: "सोमालिया" },
  { value: "BELGIUM", label: "बेल्जियम" },
  { value: "SYRIA", label: "सिरिया" },
  { value: "FESTIVAL", label: "चाड" },
  { value: "TOGO", label: "टोगो" },
  { value: "THAILAND", label: "थाईल्याण्ड" },
  { value: "TAJIKISTAN", label: "ताजिकस्तान" },
  { value: "BITE", label: "टोक्यो" },
  { value: "TUNISIA", label: "ट्युनिसिया" },
  { value: "TONGA", label: "टोङगा" },
  { value: "EAST_TIMOR", label: "पूर्वी टिमोर" },
  { value: "TURKEY", label: "टर्की" },
  { value: "BULGARIA", label: "बुल्गेरिया" },
  { value: "TAIWAN", label: "ताइवान" },
  { value: "TANZANIA", label: "तान्जानिया" },
  { value: "DUNGLAND", label: "डङ्गल्याण्ड" },
  { value: "UKRAINE", label: "युक्रेन" },
  { value: "UGANDA", label: "युगान्डा" },
  { value: "UNITED_NATIONS", label: "संयुक्त राष्ट्र संघ" },
  { value: "UNITED_STATES_OF_AMERICA", label: "संयुक्त राज्य अमेरिका" },
  { value: "URUGUAY", label: "उरुग्वै" },
  { value: "UZBEKISTAN", label: "उज्वेकिस्तान" },
  { value: "BAHRAIN", label: "बहराईन" },
  { value: "VATICAN_CITY", label: "भ्याटिकन सिटी" },
  { value: "VENEZUELA", label: "भेनेजुएला" },
  { value: "VIETNAM", label: "भियतनाम" },
  { value: "FLOUR", label: "भान्\u200cआटा" },
  { value: "WELLS", label: "वेल्स" },
  { value: "WESTERN_SAMOA", label: "पश्चिमी समोआ" },
  { value: "YEMEN", label: "यमन" },
  { value: "TOKYO", label: "टोकियो" },
  { value: "YUGOSLAVIA", label: "युगोस्लाभिया" },
  { value: "SOUTH_AFRICA", label: "दक्षिण अफ्रिका" },
  { value: "BURUNDI", label: "बुरुन्डी" },
  { value: "ZAMBIA", label: "जाम्बिया" },
  { value: "ZAIRE", label: "जायर" },
  { value: "ZIMBABWE", label: "जिम्बावै" },
  { value: "KOSOVO", label: "कोसोभो" },
  { value: "BRUNEI", label: "ब्रुनाई" },
  { value: "BOLIVIA", label: "बोलिभिया" },
  { value: "BRAZIL", label: "ब्राजिल" },
  { value: "UNITED_ARAB_EMIRATES", label: "संयुक्त अरब ईमिरेटस" },
  { value: "BAHAMAS", label: "बहामास" },
  { value: "BHUTAN", label: "भूटान" },
  { value: "BOTSWANA", label: "बोत्स्वाना" },
  { value: "BELARUS", label: "बैलारुस" },
  { value: "CANADA", label: "क्यानडा" },
  { value: "CAMBODIA", label: "कम्बोडीया" },
  { value: "CONGO", label: "कंगो" },
  { value: "SWITZERLAND", label: "स्विटजरल्याण्ड" },
  { value: "CROATIA", label: "क्रोएसिया" },
  { value: "CHILE", label: "चिली" },
  { value: "AFGHANISTAN", label: "अफगानिस्तान" },
  { value: "CAMEROON", label: "क्यामरुन" },
  { value: "CHINA", label: "चीन" },
  { value: "COLOMBIA", label: "कोलम्बीया" },
  { value: "COSTA_RICA", label: "कोष्टारिका" },
  { value: "CUBA", label: "क्युवा" },
  { value: "CYPRUS", label: "साईप्रस" },
  { value: "CZECHOSLOVAKIA", label: "चेकोस्लोभाकिया" },
  { value: "GERMANY", label: "जर्मनी" },
  { value: "DUBAI", label: "दुवैइ " },
  { value: "DENMARK", label: "डेनमार्क" },
  { value: "ALBANIA", label: "अल्बानिया" },
  { value: "DOMINICA", label: "डोमिनीका" },
  { value: "ALGERIA", label: "अल्जेरिया" },
  { value: "ECUADOR", label: "इक्वेडर" },
  { value: "EGYPT", label: "इजिप्ट" },
  { value: "SPAIN", label: "स्पेन" },
  { value: "ETHIOPIA", label: "इथियोपिया" },
  { value: "FINLAND", label: "फिन्ल्याण्ड" },
  { value: "FIJI", label: "फिजी" },
  { value: "FAWNS", label: "फान्स" },
  { value: "UNITED_KINGDOM_OF_GREAT_BRITAIN", label: "संयुक्त अधिराज्य बेलायत" },
  { value: "ARMENIA", label: "अर्मनिया" },
  { value: "GHANA", label: "घाना" },
  { value: "GAMBIA", label: "गाम्बिया" },
  { value: "GUINEA", label: "गिनी" },
  { value: "GREECE", label: "ग्रीस" },
  { value: "GUATEMALA", label: "ग्वाटेमाला" },
  { value: "HONG_KONG", label: "हङकङ" },
  { value: "THE_AIR", label: "हवाई" },
  { value: "HAITI", label: "हाइटी" },
  { value: "HUNGARY", label: "हङ्गेरि" },
  { value: "INDONESIA", label: "ईण्डोनेसिया" },
  { value: "ANGOLA", label: "अङ्गोला" },
  { value: "REPUBLIC_OF_IRELAND", label: "आयरल्याण्ड रिपब्लीक" },
  { value: "ISRAEL", label: "ईजरायल" },
  { value: "INDIA", label: "भारत" },
  { value: "IRAQ", label: "इराक" },
  { value: "IRAN", label: "इरान" },
  { value: "ICELAND", label: "आईसल्याण्ड" },
  { value: "ITALY", label: "ईटाली" },
  { value: "JAMAICA", label: "जमैका" },
  { value: "JORDAN", label: "जोर्डन" },
  { value: "JAPAN", label: "जापान" },
  { value: "ARGENTINA", label: "अर्जेन्टिना" },
  { value: "KENYA", label: "केन्या" },
  { value: "NORTH_KOREA", label: "उत्तर कोरिया" },
  { value: "SOUTH_KOREA", label: "दक्षिण कोरिया" },
  { value: "KATHMANDU", label: "काठमाण्डौ" },
  { value: "KRVET", label: "कृ्\u200cवेत" },
  { value: "KAZAKHSTAN", label: "काजकस्तान" },
  { value: "ARSHATYA", label: "अर्षट्या" },
  { value: "LEBANON", label: "लेवनान" },
  { value: "HERZEGOVINA", label: "हर्जगोभिना" },
  { value: "AUSTRALIA", label: "अष्ट्रेलिया" },
  { value: "SRI_LANKA", label: "श्रीलंका" },
  { value: "LIBERIA", label: "लाईबैेरिया" },
  { value: "LESOTHO", label: "लिसोथो" },
  { value: "LUXEMBOURG", label: "लक्जेम्वर्ग" },
  { value: "LEON", label: "लियोन" },
  { value: "LIBYA", label: "लिबिया" },
  { value: "MOROCCO", label: "मोरक्को" },
  { value: "MONACO", label: "मोनाको" },
  { value: "MADAGASCAR", label: "माडागास्कर" },
  { value: "THE_GARDENER", label: "माली" },
  { value: "ARUBA", label: "अरुबा" },
  { value: "MYANMAR", label: "म्यानमार" },
  { value: "MONGOLIA", label: "मंगोलिया" },
  { value: "MACAU", label: "मकाउ" },
  { value: "MALTA", label: "माल्टा" },
  { value: "MAURITIUS", label: "मौरीसस" },
  { value: "MALDIVES", label: "माल्दिभ्स" },
  { value: "MEXICO", label: "मेक्सिको" },
  { value: "MALAYSIA", label: "मलेशिया" },
  { value: "MOZAMBIQUE", label: "मोजाम्बिक" },
  { value: "NAMIBIA", label: "नामीबिया" },
];
