-- Check if acme_ward_wise_educational_level table exists, if not create it
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_tables WHERE tablename = 'acme_ward_wise_educational_level'
    ) THEN
        CREATE TABLE acme_ward_wise_educational_level (
            id VARCHAR(36) PRIMARY KEY,
            ward_number INTEGER NOT NULL,
            educational_level_type VARCHAR(100) NOT NULL,
            population INTEGER NOT NULL,
            updated_at TIMESTAMP DEFAULT NOW(),
            created_at TIMESTAMP DEFAULT NOW()
        );
    END IF;
END
$$;

-- Insert seed data if table is empty
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM acme_ward_wise_educational_level) THEN
        INSERT INTO acme_ward_wise_educational_level (
            id, ward_number, educational_level_type, population
        )
        VALUES
        -- Ward 1
        (gen_random_uuid(), 1, 'CHILD_DEVELOPMENT_CENTER', 4),
        (gen_random_uuid(), 1, 'NURSERY', 139),
        (gen_random_uuid(), 1, 'GRADE_1', 95),
        (gen_random_uuid(), 1, 'GRADE_2', 85),
        (gen_random_uuid(), 1, 'GRADE_3', 128),
        (gen_random_uuid(), 1, 'GRADE_4', 108),
        (gen_random_uuid(), 1, 'GRADE_5', 267),
        (gen_random_uuid(), 1, 'GRADE_6', 146),
        (gen_random_uuid(), 1, 'GRADE_7', 243),
        (gen_random_uuid(), 1, 'GRADE_8', 436),
        (gen_random_uuid(), 1, 'GRADE_9', 247),
        (gen_random_uuid(), 1, 'GRADE_10', 570),
        (gen_random_uuid(), 1, 'SLC_LEVEL', 308),
        (gen_random_uuid(), 1, 'CLASS_12_LEVEL', 453),
        (gen_random_uuid(), 1, 'BACHELOR_LEVEL', 113),
        (gen_random_uuid(), 1, 'MASTERS_LEVEL', 38),
        (gen_random_uuid(), 1, 'PHD_LEVEL', 10),
        (gen_random_uuid(), 1, 'INFORMAL_EDUCATION', 11),
        (gen_random_uuid(), 1, 'EDUCATED', 60),
        (gen_random_uuid(), 1, 'UNKNOWN', 3),
        
        -- Ward 2
        (gen_random_uuid(), 2, 'CHILD_DEVELOPMENT_CENTER', 36),
        (gen_random_uuid(), 2, 'NURSERY', 291),
        (gen_random_uuid(), 2, 'GRADE_1', 242),
        (gen_random_uuid(), 2, 'GRADE_2', 241),
        (gen_random_uuid(), 2, 'GRADE_3', 351),
        (gen_random_uuid(), 2, 'GRADE_4', 345),
        (gen_random_uuid(), 2, 'GRADE_5', 671),
        (gen_random_uuid(), 2, 'GRADE_6', 398),
        (gen_random_uuid(), 2, 'GRADE_7', 540),
        (gen_random_uuid(), 2, 'GRADE_8', 965),
        (gen_random_uuid(), 2, 'GRADE_9', 491),
        (gen_random_uuid(), 2, 'GRADE_10', 988),
        (gen_random_uuid(), 2, 'SLC_LEVEL', 1101),
        (gen_random_uuid(), 2, 'CLASS_12_LEVEL', 1089),
        (gen_random_uuid(), 2, 'BACHELOR_LEVEL', 480),
        (gen_random_uuid(), 2, 'MASTERS_LEVEL', 228),
        (gen_random_uuid(), 2, 'PHD_LEVEL', 67),
        (gen_random_uuid(), 2, 'INFORMAL_EDUCATION', 43),
        (gen_random_uuid(), 2, 'OTHER', 2),
        (gen_random_uuid(), 2, 'EDUCATED', 93),
        (gen_random_uuid(), 2, 'UNKNOWN', 14),
        
        -- Ward 3
        (gen_random_uuid(), 3, 'CHILD_DEVELOPMENT_CENTER', 18),
        (gen_random_uuid(), 3, 'NURSERY', 312),
        (gen_random_uuid(), 3, 'GRADE_1', 183),
        (gen_random_uuid(), 3, 'GRADE_2', 164),
        (gen_random_uuid(), 3, 'GRADE_3', 212),
        (gen_random_uuid(), 3, 'GRADE_4', 200),
        (gen_random_uuid(), 3, 'GRADE_5', 482),
        (gen_random_uuid(), 3, 'GRADE_6', 250),
        (gen_random_uuid(), 3, 'GRADE_7', 313),
        (gen_random_uuid(), 3, 'GRADE_8', 639),
        (gen_random_uuid(), 3, 'GRADE_9', 358),
        (gen_random_uuid(), 3, 'GRADE_10', 863),
        (gen_random_uuid(), 3, 'SLC_LEVEL', 773),
        (gen_random_uuid(), 3, 'CLASS_12_LEVEL', 1280),
        (gen_random_uuid(), 3, 'BACHELOR_LEVEL', 536),
        (gen_random_uuid(), 3, 'MASTERS_LEVEL', 240),
        (gen_random_uuid(), 3, 'PHD_LEVEL', 26),
        (gen_random_uuid(), 3, 'INFORMAL_EDUCATION', 44),
        (gen_random_uuid(), 3, 'OTHER', 12),
        (gen_random_uuid(), 3, 'EDUCATED', 184),
        (gen_random_uuid(), 3, 'UNKNOWN', 39),
        
        -- Ward 4
        (gen_random_uuid(), 4, 'CHILD_DEVELOPMENT_CENTER', 13),
        (gen_random_uuid(), 4, 'NURSERY', 237),
        (gen_random_uuid(), 4, 'GRADE_1', 137),
        (gen_random_uuid(), 4, 'GRADE_2', 171),
        (gen_random_uuid(), 4, 'GRADE_3', 203),
        (gen_random_uuid(), 4, 'GRADE_4', 191),
        (gen_random_uuid(), 4, 'GRADE_5', 441),
        (gen_random_uuid(), 4, 'GRADE_6', 240),
        (gen_random_uuid(), 4, 'GRADE_7', 309),
        (gen_random_uuid(), 4, 'GRADE_8', 558),
        (gen_random_uuid(), 4, 'GRADE_9', 307),
        (gen_random_uuid(), 4, 'GRADE_10', 657),
        (gen_random_uuid(), 4, 'SLC_LEVEL', 555),
        (gen_random_uuid(), 4, 'CLASS_12_LEVEL', 733),
        (gen_random_uuid(), 4, 'BACHELOR_LEVEL', 203),
        (gen_random_uuid(), 4, 'MASTERS_LEVEL', 69),
        (gen_random_uuid(), 4, 'PHD_LEVEL', 17),
        (gen_random_uuid(), 4, 'INFORMAL_EDUCATION', 29),
        (gen_random_uuid(), 4, 'OTHER', 9),
        (gen_random_uuid(), 4, 'EDUCATED', 57),
        (gen_random_uuid(), 4, 'UNKNOWN', 47),
        
        -- Ward 5
        (gen_random_uuid(), 5, 'CHILD_DEVELOPMENT_CENTER', 37),
        (gen_random_uuid(), 5, 'NURSERY', 222),
        (gen_random_uuid(), 5, 'GRADE_1', 275),
        (gen_random_uuid(), 5, 'GRADE_2', 255),
        (gen_random_uuid(), 5, 'GRADE_3', 281),
        (gen_random_uuid(), 5, 'GRADE_4', 251),
        (gen_random_uuid(), 5, 'GRADE_5', 463),
        (gen_random_uuid(), 5, 'GRADE_6', 237),
        (gen_random_uuid(), 5, 'GRADE_7', 262),
        (gen_random_uuid(), 5, 'GRADE_8', 299),
        (gen_random_uuid(), 5, 'GRADE_9', 168),
        (gen_random_uuid(), 5, 'GRADE_10', 332),
        (gen_random_uuid(), 5, 'SLC_LEVEL', 36),
        (gen_random_uuid(), 5, 'CLASS_12_LEVEL', 301),
        (gen_random_uuid(), 5, 'BACHELOR_LEVEL', 31),
        (gen_random_uuid(), 5, 'MASTERS_LEVEL', 8),
        (gen_random_uuid(), 5, 'PHD_LEVEL', 2),
        (gen_random_uuid(), 5, 'OTHER', 18),
        (gen_random_uuid(), 5, 'EDUCATED', 112),
        (gen_random_uuid(), 5, 'UNKNOWN', 13),
        
        -- Ward 6
        (gen_random_uuid(), 6, 'CHILD_DEVELOPMENT_CENTER', 93),
        (gen_random_uuid(), 6, 'NURSERY', 255),
        (gen_random_uuid(), 6, 'GRADE_1', 228),
        (gen_random_uuid(), 6, 'GRADE_2', 270),
        (gen_random_uuid(), 6, 'GRADE_3', 327),
        (gen_random_uuid(), 6, 'GRADE_4', 382),
        (gen_random_uuid(), 6, 'GRADE_5', 644),
        (gen_random_uuid(), 6, 'GRADE_6', 423),
        (gen_random_uuid(), 6, 'GRADE_7', 414),
        (gen_random_uuid(), 6, 'GRADE_8', 643),
        (gen_random_uuid(), 6, 'GRADE_9', 316),
        (gen_random_uuid(), 6, 'GRADE_10', 639),
        (gen_random_uuid(), 6, 'SLC_LEVEL', 201),
        (gen_random_uuid(), 6, 'CLASS_12_LEVEL', 473),
        (gen_random_uuid(), 6, 'BACHELOR_LEVEL', 89),
        (gen_random_uuid(), 6, 'MASTERS_LEVEL', 15),
        (gen_random_uuid(), 6, 'PHD_LEVEL', 10),
        (gen_random_uuid(), 6, 'INFORMAL_EDUCATION', 2),
        (gen_random_uuid(), 6, 'OTHER', 1),
        (gen_random_uuid(), 6, 'EDUCATED', 58),
        (gen_random_uuid(), 6, 'UNKNOWN', 2),
        
        -- Ward 7
        (gen_random_uuid(), 7, 'CHILD_DEVELOPMENT_CENTER', 14),
        (gen_random_uuid(), 7, 'NURSERY', 215),
        (gen_random_uuid(), 7, 'GRADE_1', 237),
        (gen_random_uuid(), 7, 'GRADE_2', 257),
        (gen_random_uuid(), 7, 'GRADE_3', 340),
        (gen_random_uuid(), 7, 'GRADE_4', 330),
        (gen_random_uuid(), 7, 'GRADE_5', 517),
        (gen_random_uuid(), 7, 'GRADE_6', 306),
        (gen_random_uuid(), 7, 'GRADE_7', 321),
        (gen_random_uuid(), 7, 'GRADE_8', 470),
        (gen_random_uuid(), 7, 'GRADE_9', 281),
        (gen_random_uuid(), 7, 'GRADE_10', 496),
        (gen_random_uuid(), 7, 'SLC_LEVEL', 233),
        (gen_random_uuid(), 7, 'CLASS_12_LEVEL', 561),
        (gen_random_uuid(), 7, 'BACHELOR_LEVEL', 134),
        (gen_random_uuid(), 7, 'MASTERS_LEVEL', 47),
        (gen_random_uuid(), 7, 'PHD_LEVEL', 17),
        (gen_random_uuid(), 7, 'INFORMAL_EDUCATION', 14),
        (gen_random_uuid(), 7, 'OTHER', 14),
        (gen_random_uuid(), 7, 'EDUCATED', 76),
        (gen_random_uuid(), 7, 'UNKNOWN', 85),
        
        -- Ward 8
        (gen_random_uuid(), 8, 'CHILD_DEVELOPMENT_CENTER', 35),
        (gen_random_uuid(), 8, 'NURSERY', 101),
        (gen_random_uuid(), 8, 'GRADE_1', 148),
        (gen_random_uuid(), 8, 'GRADE_2', 219),
        (gen_random_uuid(), 8, 'GRADE_3', 201),
        (gen_random_uuid(), 8, 'GRADE_4', 198),
        (gen_random_uuid(), 8, 'GRADE_5', 373),
        (gen_random_uuid(), 8, 'GRADE_6', 213),
        (gen_random_uuid(), 8, 'GRADE_7', 190),
        (gen_random_uuid(), 8, 'GRADE_8', 361),
        (gen_random_uuid(), 8, 'GRADE_9', 179),
        (gen_random_uuid(), 8, 'GRADE_10', 444),
        (gen_random_uuid(), 8, 'SLC_LEVEL', 179),
        (gen_random_uuid(), 8, 'CLASS_12_LEVEL', 355),
        (gen_random_uuid(), 8, 'BACHELOR_LEVEL', 121),
        (gen_random_uuid(), 8, 'MASTERS_LEVEL', 33),
        (gen_random_uuid(), 8, 'PHD_LEVEL', 6),
        (gen_random_uuid(), 8, 'INFORMAL_EDUCATION', 18),
        (gen_random_uuid(), 8, 'OTHER', 12),
        (gen_random_uuid(), 8, 'EDUCATED', 20),
        (gen_random_uuid(), 8, 'UNKNOWN', 2);
    END IF;
END
$$;
