import { z } from "zod";

// Define the language type enum to match the database enum
export const LanguageTypeEnum = z.enum([
  "NEPALI",
  "LIMBU",
  "RAI",
  "HINDI",
  "NEWARI",
  "SHERPA",
  "TAMANG",
  "MAITHILI",
  "BHOJPURI",
  "THARU",
  "BAJJIKA",
  "MAGAR",
  "DOTELI",
  "URDU",
  "AWADI",
  "GURUNG",
  "BAITADELI",
  "AACHAMI",
  "BANTAWA",
  "RAJBANSHI",
  "CHAMLING",
  "BAJHANGI",
  "SANTHALI",
  "CHEPANG",
  "DANUWAR",
  "SUNUWAR",
  "MAGAHI",
  "URAUN",
  "KULUNG",
  "KHAM",
  "RAJASTHANI",
  "MAJHI",
  "THAMI",
  "BHUJEL",
  "BANGALA",
  "THULUNG",
  "YAKKHA",
  "DHIMAL",
  "TAJPURIYA",
  "ANGIKA",
  "SAMPANG",
  "KHALING",
  "YAMBULE",
  "KUMAL",
  "DARAI",
  "BAHING",
  "BAJURELI",
  "HYOLMO",
  "NACHIRING",
  "YAMPHU",
  "BOTE",
  "GHARE",
  "DUMI",
  "LAPCHA",
  "PUMA",
  "DUMANGLI",
  "DARCHULELI",
  "AATHPAHARIYA",
  "THAKALI",
  "JIREL",
  "MEWAHANG",
  "SYMBOLIC_LANGUAGE",
  "TIBETIAN",
  "MECHE",
  "CHANTYAL",
  "RAJI",
  "LOHARUNG",
  "CHINTANG",
  "GANGAI",
  "PAHARI",
  "DAILEKHI",
  "LHOPA",
  "DURA",
  "KOCHE",
  "CHILING",
  "ENGLISH",
  "JERO",
  "KHAS",
  "SANSKRIT",
  "DOLPALI",
  "HAYU",
  "TILUNG",
  "KOYI",
  "KISAN",
  "WALING",
  "MUSALMAN",
  "HIRAYANWI",
  "JUMLI",
  "PUNJABI",
  "LHOMI",
  "BELHARI",
  "ORIYA",
  "SONAHA",
  "SINDHI",
  "DADELDHURI",
  "BYANSI",
  "AASAMI",
  "KAHMCHI",
  "SAAM",
  "MANAGE",
  "DHULELI",
  "PHANGDUWALI",
  "SUREL",
  "MALPANDE",
  "CHINESE",
  "KHARIYA",
  "KURMALI",
  "BARAM",
  "LINGKHIM",
  "SADHANI",
  "KAGATE",
  "JONGKHA",
  "BANKARIYA",
  "KAIKE",
  "GADHWALI",
  "FRECHN",
  "MIJO",
  "KUKI",
  "KUSUNDA",
  "RUSSIAN",
  "SPANISH",
  "NAGAMIJ",
  "ARABI",
  "OTHER",
]);
export type LanguageType = z.infer<typeof LanguageTypeEnum>;

// Schema for ward-wise mother tongue population data
export const wardWiseMotherTonguePopulationSchema = z.object({
  id: z.string().optional(),
  wardNumber: z.number().int().positive(),
  languageType: LanguageTypeEnum,
  population: z.number().int().nonnegative(),
});

// Schema for filtering ward-wise mother tongue population data
export const wardWiseMotherTonguePopulationFilterSchema = z.object({
  wardNumber: z.number().int().positive().optional(),
  languageType: LanguageTypeEnum.optional(),
});

export const updateWardWiseMotherTonguePopulationSchema =
  wardWiseMotherTonguePopulationSchema;

export type WardWiseMotherTonguePopulationData = z.infer<
  typeof wardWiseMotherTonguePopulationSchema
>;
export type UpdateWardWiseMotherTonguePopulationData =
  WardWiseMotherTonguePopulationData;
export type WardWiseMotherTonguePopulationFilter = z.infer<
  typeof wardWiseMotherTonguePopulationFilterSchema
>;
