# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SafeMaternityData",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "indicator",
                    models.CharField(
                        choices=[
                            ("FIRST_ANTENATAL_CHECKUP", "पहिलो गर्भजाँच"),
                            ("FOUR_ANTENATAL_CHECKUPS", "चार पटक गर्भ जाच गर्ने प्रतिशत"),
                            ("INSTITUTIONAL_DELIVERY", "संस्थागत प्रशुती संख्या"),
                            (
                                "POSTNATAL_CHECKUP_24_HOURS",
                                "२४ घण्टा भित्र सुत्केरी जाँचको प्रतिशत",
                            ),
                            ("FOUR_POSTNATAL_CHECKUPS", "चार पटक सुत्केरी जाँचको प्रतिशत"),
                            ("MATERNAL_MORTALITY_RATE", "मातृ मृत्युको प्रतिशत"),
                        ],
                        max_length=30,
                        verbose_name="सूचक",
                    ),
                ),
                ("year", models.CharField(max_length=50, verbose_name="वर्ष")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=6, verbose_name="मान"
                    ),
                ),
            ],
            options={
                "verbose_name": "सुरक्षित मातृत्व तथ्यांक",
                "verbose_name_plural": "सुरक्षित मातृत्व तथ्यांक",
                "unique_together": {("indicator", "year")},
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=200, verbose_name="विद्यालयको नाम"),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("COMMUNITY", "सामुदायिक"),
                            ("INSTITUTIONAL", "संस्थागत"),
                            ("MADRASA", "मदरसा"),
                            ("GUMBA", "गुम्बा"),
                            ("BOARDING", "बोर्डिङ"),
                        ],
                        default="COMMUNITY",
                        max_length=15,
                        verbose_name="विद्यालयको प्रकार",
                    ),
                ),
            ],
            options={
                "verbose_name": "विद्यालय",
                "verbose_name_plural": "विद्यालयहरू",
                "unique_together": {("ward_number", "school_name")},
            },
        ),
        migrations.CreateModel(
            name="WardAgeGenderWiseFirstMarriageAge",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "first_marriage_age_group",
                    models.CharField(
                        choices=[
                            ("AGE_0_14", "०-१४ वर्ष"),
                            ("AGE_15_19", "१५-१९ वर्ष"),
                            ("AGE_20_24", "२०-२४ वर्ष"),
                            ("AGE_25_29", "२५-२९ वर्ष"),
                            ("AGE_30_34", "३०-३४ वर्ष"),
                            ("AGE_35_39", "३५-३९ वर्ष"),
                            ("AGE_40_44", "४०-४४ वर्ष"),
                            ("AGE_45_49", "४५-४९ वर्ष"),
                            ("AGE_50_54", "५०-५४ वर्ष"),
                            ("AGE_55_59", "५५-५९ वर्ष"),
                            ("AGE_60_AND_ABOVE", "६० वर्ष र माथि"),
                        ],
                        max_length=20,
                        verbose_name="पहिलो विवाहको उमेर समूह",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "पुरुष"),
                            ("FEMALE", "महिला"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=10,
                        verbose_name="लिंग",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत उमेर लिंग अनुसार पहिलो विवाहको उमेर",
                "verbose_name_plural": "वडागत उमेर लिंग अनुसार पहिलो विवाहको उमेर",
                "unique_together": {
                    ("ward_number", "first_marriage_age_group", "gender")
                },
            },
        ),
        migrations.CreateModel(
            name="WardWiseDisabledPopulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "disabled_population",
                    models.PositiveIntegerField(
                        default=0, verbose_name="अपाङ्गता भएको जनसंख्या"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत अपाङ्गता भएको जनसंख्या",
                "verbose_name_plural": "वडागत अपाङ्गता भएको जनसंख्या",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseDrinkingWaterSource",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "drinking_water_source",
                    models.CharField(
                        choices=[
                            ("TAP_INSIDE_HOUSE", "घर भित्र पानी ट्याप"),
                            ("TAP_OUTSIDE_HOUSE", "घर बाहिर पानी ट्याप"),
                            ("TUBEWELL", "ट्यूबवेल"),
                            ("COVERED_WELL", "ढाकेको इनार"),
                            ("OPEN_WELL", "खुला इनार"),
                            ("AQUIFIER_MOOL", "भुमिगत जलश्रोत मूल"),
                            ("RIVER", "नदी"),
                            ("JAR", "जार"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=25,
                        verbose_name="पिउने पानीको स्रोत",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत पिउने पानीको स्रोत",
                "verbose_name_plural": "वडागत पिउने पानीको स्रोत",
                "unique_together": {("ward_number", "drinking_water_source")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseEducationalInstitution",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "data_year",
                    models.CharField(
                        help_text="Nepali year (e.g., २०७९, २०८०, २०८१)",
                        max_length=10,
                        verbose_name="डेटा वर्ष",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        help_text="Full name of the educational institution",
                        max_length=255,
                        verbose_name="शैक्षिक संस्थाको नाम",
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("COMMUNITY_SCHOOL", "सामुदायिक विद्यालय"),
                            ("RELIGIOUS_SCHOOL", "धार्मिक विद्यालय"),
                            ("TECHNICAL_SCHOOL", "प्राविधिक विद्यालय"),
                            ("COMMUNITY_LEARNING_CENTER", "सामुदायिक सिकाई केन्द्र"),
                            ("PRIVATE_SCHOOL", "निजी विद्यालय"),
                            ("OTHER", "अन्य"),
                        ],
                        default="COMMUNITY_SCHOOL",
                        max_length=50,
                        verbose_name="संस्थाको प्रकार",
                    ),
                ),
                (
                    "school_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRIMARY", "प्राथमिक"),
                            ("LOWER_SECONDARY", "निम्न माध्यमिक"),
                            ("SECONDARY", "माध्यमिक"),
                            ("HIGHER_SECONDARY", "उच्च माध्यमिक"),
                            ("EARLY_CHILDHOOD", "बाल विकास केन्द्र"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="विद्यालयको तह",
                    ),
                ),
                (
                    "male_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="पुरुष विद्यार्थी संख्या"
                    ),
                ),
                (
                    "female_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="महिला विद्यार्थी संख्या"
                    ),
                ),
                (
                    "total_teachers",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="कुल शिक्षक संख्या"
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="सञ्चालनमा छ/छैन"),
                ),
            ],
            options={
                "verbose_name": "वडागत शैक्षिक संस्था र विद्यार्थी विवरण",
                "verbose_name_plural": "वडागत शैक्षिक संस्था र विद्यार्थी विवरण",
                "unique_together": {("ward_number", "data_year", "institution_name")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseEducationalLevel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "educational_level_type",
                    models.CharField(
                        choices=[
                            ("CHILD_DEVELOPMENT_CENTER", "बाल विकास केन्द्र"),
                            ("NURSERY", "नर्सरी"),
                            ("GRADE_1", "कक्षा १"),
                            ("GRADE_2", "कक्षा २"),
                            ("GRADE_3", "कक्षा ३"),
                            ("GRADE_4", "कक्षा ४"),
                            ("GRADE_5", "कक्षा ५"),
                            ("GRADE_6", "कक्षा ६"),
                            ("GRADE_7", "कक्षा ७"),
                            ("GRADE_8", "कक्षा ८"),
                            ("GRADE_9", "कक्षा ९"),
                            ("GRADE_10", "कक्षा १०"),
                            ("SLC_LEVEL", "एसएलसी तह"),
                            ("CLASS_12_LEVEL", "कक्षा १२ तह"),
                            ("BACHELOR_LEVEL", "स्नातक तह"),
                            ("MASTERS_LEVEL", "स्नातकोत्तर तह"),
                            ("PHD_LEVEL", "पीएचडी तह"),
                            ("INFORMAL_EDUCATION", "अनौपचारिक शिक्षा"),
                            ("OTHER", "अन्य"),
                            ("EDUCATED", "शिक्षित"),
                            ("UNKNOWN", "अज्ञात"),
                        ],
                        max_length=30,
                        verbose_name="शैक्षिक तह प्रकार",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत शैक्षिक तह",
                "verbose_name_plural": "वडागत शैक्षिक तह",
                "unique_together": {("ward_number", "educational_level_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHealthInstitution",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the health institution",
                        max_length=255,
                        verbose_name="स्वास्थ्य संस्थाको नाम",
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "अस्पताल"),
                            ("PRIMARY_HEALTH_CENTER", "प्राथमिक स्वास्थ्य केन्द्र"),
                            ("HEALTH_POST", "स्वास्थ्य चौकी"),
                            ("AYURVEDA_CENTER", "आयुर्वेद केन्द्र"),
                            ("COMMUNITY_HEALTH_UNIT", "सामुदायिक स्वास्थ्य इकाइ"),
                            ("SUB_HEALTH_POST", "उप स्वास्थ्य चौकी"),
                            ("BIRTHING_CENTER", "प्रसूति केन्द्र"),
                            ("CLINIC", "क्लिनिक"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=50,
                        verbose_name="संस्थाको प्रकार",
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत स्वास्थ्य संस्था विवरण",
                "verbose_name_plural": "वडागत स्वास्थ्य संस्था विवरण",
                "unique_together": {("ward_number", "name")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseLiteracyStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "literacy_type",
                    models.CharField(
                        choices=[
                            ("BOTH_READING_AND_WRITING", "पढ्न र लेख्न दुवै"),
                            ("READING_ONLY", "पढ्न मात्र"),
                            ("ILLITERATE", "निरक्षर"),
                        ],
                        max_length=25,
                        verbose_name="साक्षरता प्रकार",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत साक्षरता अवस्था",
                "verbose_name_plural": "वडागत साक्षरता अवस्था",
                "unique_together": {("ward_number", "literacy_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseMajorSubject",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("ENGLISH", "अंग्रेजी"),
                            ("ECONOMICS", "अर्थशास्त्र"),
                            ("ENGINEERING", "इन्जिनियरिङ"),
                            ("HISTORY", "इतिहास"),
                            ("HOME_ECONOMICS", "गृह अर्थशास्त्र"),
                            ("RURAL_DEVELOPMENT", "ग्रामीण विकास"),
                            ("MEDICINE", "चिकित्सा"),
                            ("POPULATION_STUDY", "जनसंख्या अध्ययन"),
                            ("BIOLOGY", "जैविक विज्ञान"),
                            ("STATISTICS", "तथ्यांक"),
                            ("NEPALI", "नेपाली"),
                            ("TOURISM", "पर्यटन"),
                            ("GEOGRAPHY", "भूगोल"),
                            ("PHYSICS", "भौतिकशास्त्र"),
                            ("PSYCHOLOGY", "मनोविज्ञान"),
                            ("HUMANITIES", "मानविकी"),
                            ("CHEMISTRY", "रसायनशास्त्र"),
                            ("POLITICAL_SCIENCE", "राजनीति विज्ञान"),
                            ("FORESTRY_AND_AGRICULTURE", "वन तथा कृषि"),
                            ("BOTANY", "वनस्पति विज्ञान"),
                            ("COMMERCE", "वाणिज्य"),
                            ("SCIENCE", "विज्ञान"),
                            ("MANAGEMENT", "व्यवस्थापन"),
                            ("EDUCATION", "शिक्षा"),
                            ("EDUCATIONAL_SCIENCE", "शिक्षा विज्ञान"),
                            ("SANSKRIT", "संस्कृत"),
                            ("ARTS", "कला"),
                            ("SOCIAL_SCIENCES", "सामाजिक विज्ञान"),
                            ("INFORMATION_TECHNOLOGY", "सूचना प्रविधि"),
                            ("HINDI", "हिन्दी"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=30,
                        verbose_name="मुख्य विषय प्रकार",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत मुख्य विषय",
                "verbose_name_plural": "वडागत मुख्य विषय",
                "unique_together": {("ward_number", "subject_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseOldAgePopulationAndSingleWomen",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "male_old_age_population",
                    models.PositiveIntegerField(
                        default=0, verbose_name="पुरुष जेष्ठ नागरिक जनसंख्या"
                    ),
                ),
                (
                    "female_old_age_population",
                    models.PositiveIntegerField(
                        default=0, verbose_name="महिला जेष्ठ नागरिक जनसंख्या"
                    ),
                ),
                (
                    "single_women_population",
                    models.PositiveIntegerField(
                        default=0, verbose_name="एकल महिला जनसंख्या"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत जेष्ठ नागरिक र एकल महिला जनसंख्या",
                "verbose_name_plural": "वडागत जेष्ठ नागरिक र एकल महिला जनसंख्या",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseSchoolDropout",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("LIMITED_SPACE", "सीमित ठाउँ"),
                            ("EXPENSIVE", "महँगो"),
                            ("FAR", "टाढा"),
                            ("HOUSE_HELP", "घरको काम"),
                            ("UNWILLING_PARENTS", "अनिच्छुक अभिभावक"),
                            ("WANTED_STUDY_COMPLETED", "अध्ययन पूरा गर्न चाहना"),
                            ("MARRIAGE", "विवाह"),
                            ("EMPLOYMENT", "रोजगारी"),
                            ("UNKNOWN", "अज्ञात"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=25,
                        verbose_name="विद्यालय छाड्नुको कारण",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत विद्यालय छाड्नुको कारण",
                "verbose_name_plural": "वडागत विद्यालय छाड्नुको कारण",
                "unique_together": {("ward_number", "cause")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseSolidWasteManagement",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "solid_waste_management",
                    models.CharField(
                        choices=[
                            ("HOME_COLLECTION", "घर संकलन"),
                            ("WASTE_COLLECTING_PLACE", "फोहोर संकलन ठाउँ"),
                            ("BURNING", "जलाउने"),
                            ("DIGGING", "गाड्ने"),
                            ("RIVER", "नदी"),
                            ("ROAD_OR_PUBLIC_PLACE", "सडक वा सार्वजनिक ठाउँ"),
                            ("COMPOST_MANURE", "कम्पोस्ट मल"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=25,
                        verbose_name="ठोस फोहोर व्यवस्थापन",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत ठोस फोहोर व्यवस्थापन",
                "verbose_name_plural": "वडागत ठोस फोहोर व्यवस्थापन",
                "unique_together": {("ward_number", "solid_waste_management")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseTeacherStaffing",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=255, verbose_name="विद्यालयको नाम"),
                ),
                (
                    "institution_level",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "प्राथमिक"),
                            ("LOWER_SECONDARY", "निम्न माध्यमिक"),
                            ("SECONDARY", "माध्यमिक"),
                            ("HIGHER_SECONDARY", "उच्च माध्यमिक"),
                            ("EARLY_CHILDHOOD", "बाल विकास केन्द्र"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="संस्थाको तह",
                    ),
                ),
                (
                    "teacher_level",
                    models.CharField(
                        choices=[
                            ("CHILD_DEVELOPMENT", "बाल विकास"),
                            ("BASIC_1_5", "आधारभूत १-५"),
                            ("BASIC_6_8", "आधारभूत ६-८"),
                            ("BASIC_9_10", "आधारभूत ९-१०"),
                            ("BASIC_11_12", "आधारभूत ११-१२"),
                        ],
                        max_length=30,
                        verbose_name="शिक्षकको तह",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("APPROVED_QUOTA", "स्वीकृत दरबन्दी"),
                            ("RELIEF", "राहत"),
                            ("FEDERAL_GRANT", "संघीय अनुदान"),
                            ("RM_GRANT", "गाउँपालिका अनुदान"),
                            ("PRIVATE_SOURCE", "निजी स्रोत"),
                        ],
                        max_length=30,
                        verbose_name="पदको प्रकार",
                    ),
                ),
                (
                    "teacher_count",
                    models.PositiveIntegerField(default=0, verbose_name="शिक्षक संख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत शिक्षक र शैक्षिक जनशक्ति",
                "verbose_name_plural": "वडागत शिक्षक र शैक्षिक जनशक्ति",
                "db_table": "social_ward_wise_teacher_staffing",
                "unique_together": {
                    ("ward_number", "school_name", "teacher_level", "position_type")
                },
            },
        ),
        migrations.CreateModel(
            name="WardWiseTeacherSummary",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher_level",
                    models.CharField(
                        choices=[
                            ("CHILD_DEVELOPMENT", "बाल विकास"),
                            ("BASIC_1_5", "आधारभूत १-५"),
                            ("BASIC_6_8", "आधारभूत ६-८"),
                            ("BASIC_9_10", "आधारभूत ९-१०"),
                            ("BASIC_11_12", "आधारभूत ११-१२"),
                        ],
                        max_length=30,
                        verbose_name="शिक्षकको तह",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("APPROVED_QUOTA", "स्वीकृत दरबन्दी"),
                            ("RELIEF", "राहत"),
                            ("FEDERAL_GRANT", "संघीय अनुदान"),
                            ("RM_GRANT", "गाउँपालिका अनुदान"),
                            ("PRIVATE_SOURCE", "निजी स्रोत"),
                        ],
                        max_length=30,
                        verbose_name="पदको प्रकार",
                    ),
                ),
                (
                    "total_teachers",
                    models.PositiveIntegerField(default=0, verbose_name="कुल शिक्षक"),
                ),
            ],
            options={
                "verbose_name": "शिक्षक र शैक्षिक जनशक्ति सारांश",
                "verbose_name_plural": "शिक्षक र शैक्षिक जनशक्ति सारांश",
                "db_table": "social_ward_wise_teacher_summary",
                "unique_together": {("teacher_level", "position_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseTimeToHealthOrganization",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "time_to_health_organization",
                    models.CharField(
                        choices=[
                            ("UNDER_15_MIN", "१५ मिनेट मुनि"),
                            ("UNDER_30_MIN", "३० मिनेट मुनि"),
                            ("UNDER_1_HOUR", "१ घण्टा मुनि"),
                            ("1_HOUR_OR_MORE", "१ घण्टा वा बढी"),
                        ],
                        max_length=20,
                        verbose_name="स्वास्थ्य संस्था पुग्न लाग्ने समय",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत स्वास्थ्य संस्था पहुँच समय",
                "verbose_name_plural": "वडागत स्वास्थ्य संस्था पहुँच समय",
                "unique_together": {("ward_number", "time_to_health_organization")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseToiletType",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "toilet_type",
                    models.CharField(
                        choices=[
                            ("FLUSH_WITH_SEPTIC_TANK", "सेप्टिक ट्यांक सहित फ्लश"),
                            ("NORMAL", "सामान्य"),
                            ("PUBLIC_EILANI", "सार्वजनिक ऐलानी"),
                            ("NO_TOILET", "शौचालय छैन"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=25,
                        verbose_name="शौचालयको प्रकार",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत शौचालयको प्रकार",
                "verbose_name_plural": "वडागत शौचालयको प्रकार",
                "unique_together": {("ward_number", "toilet_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseVaccinationData",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "indicator",
                    models.CharField(
                        choices=[
                            ("BCG", "बीसीजी"),
                            ("MEASLES", "दादुरा"),
                            ("HEPATITIS_B", "हेपाटाइटिस बी"),
                            ("PNEUMONIA", "निमोनिया"),
                            ("POLIO", "पोलियो"),
                            ("TETANUS", "धनुष्टंकार"),
                            ("DPT", "डीपीटी"),
                            ("JAPANESE_ENCEPHALITIS", "जापानी मस्तिष्क ज्वरो"),
                        ],
                        max_length=25,
                        verbose_name="सूचक",
                    ),
                ),
                ("year", models.CharField(max_length=20, verbose_name="वर्ष")),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="प्रतिशत",
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत खोप तथ्यांक",
                "verbose_name_plural": "वडागत खोप तथ्यांक",
                "unique_together": {("ward_number", "indicator", "year")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseWaterPurification",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "water_purification",
                    models.CharField(
                        choices=[
                            ("BOILING", "उमालेर"),
                            ("FILTERING", "छानेर"),
                            ("CHEMICAL_PIYUSH", "रसायनिक पियुष"),
                            ("NO_ANY_FILTERING", "कुनै छनौट नगर्ने"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="पानी शुद्धिकरण",
                    ),
                ),
                (
                    "households",
                    models.PositiveIntegerField(default=0, verbose_name="घरपरिवार"),
                ),
            ],
            options={
                "verbose_name": "वडागत पानी शुद्धिकरण",
                "verbose_name_plural": "वडागत पानी शुद्धिकरण",
                "unique_together": {("ward_number", "water_purification")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseYouthSchoolAttendance",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("AGE_5_9", "५-९ वर्ष"),
                            ("AGE_10_14", "१०-१४ वर्ष"),
                            ("AGE_15_19", "१५-१९ वर्ष"),
                            ("AGE_20_24", "२०-२४ वर्ष"),
                            ("AGE_25", "२५ वर्ष"),
                        ],
                        max_length=15,
                        verbose_name="उमेर समूह",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "पुरुष"),
                            ("FEMALE", "महिला"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=10,
                        verbose_name="लिंग",
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("ATTENDING", "विद्यालय जाने"),
                            ("NOT_ATTENDING", "विद्यालय नजाने"),
                        ],
                        max_length=15,
                        verbose_name="विद्यालय उपस्थिति अवस्था",
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत युवा विद्यालय उपस्थिति",
                "verbose_name_plural": "वडागत युवा विद्यालय उपस्थिति",
                "unique_together": {
                    ("ward_number", "age_group", "gender", "attendance_status")
                },
            },
        ),
        migrations.CreateModel(
            name="WardYearWiseCommonDiseases",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "disease_type",
                    models.CharField(
                        choices=[
                            ("FEVER", "ज्वरो"),
                            ("COUGH", "खोकी"),
                            ("ABDOMINAL_PAIN", "पेट दुखाइ"),
                            ("ITCHING", "चिलाउने"),
                            ("FATIGUE_AND_WEAKNESS", "थकान र कमजोरी"),
                            ("ARTHRITIS", "गठिया"),
                            ("CHEST_PAIN", "छाती दुखाइ"),
                            ("ORAL_STOMATITIS", "मुखको घाउ"),
                            ("DIZZINESS_AND_VERTIGO", "चक्कर लाग्ने"),
                            ("SHORTNESS_OF_BREATH", "सास फेर्न गाह्रो"),
                        ],
                        max_length=40,
                        verbose_name="रोगको नाम",
                    ),
                ),
                ("year", models.CharField(max_length=20, verbose_name="वर्ष")),
                (
                    "case_count",
                    models.PositiveIntegerField(default=0, verbose_name="बिरामी संख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत रोग तथ्यांक",
                "verbose_name_plural": "वडागत रोग तथ्यांक",
                "unique_together": {("ward_number", "disease_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="SchoolStudentData",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.CharField(max_length=10, verbose_name="वर्ष")),
                (
                    "female_students",
                    models.PositiveIntegerField(default=0, verbose_name="छात्रा"),
                ),
                (
                    "male_students",
                    models.PositiveIntegerField(default=0, verbose_name="छात्र"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_data",
                        to="social.school",
                        verbose_name="विद्यालय",
                    ),
                ),
            ],
            options={
                "verbose_name": "विद्यालय विद्यार्थी तथ्यांक",
                "verbose_name_plural": "विद्यालय विद्यार्थी तथ्यांक",
                "unique_together": {("school", "year")},
            },
        ),
    ]
