# Generated by Django 5.2.3 on 2025-06-23 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("chart_key", models.CharField(max_length=255, unique=True)),
                ("chart_type", models.CharField(max_length=20)),
                ("file_path", models.CharField(max_length=500)),
                ("title", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
