# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chart_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chartfile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="सिर्जनाकर्ता",
            ),
        ),
        migrations.AddField(
            model_name="chartfile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="अपडेटकर्ता",
            ),
        ),
        migrations.AddIndex(
            model_name="chartfile",
            index=models.Index(
                fields=["chart_key"], name="chart_manag_chart_k_692ea4_idx"
            ),
        ),
    ]
