export * from "./demographics";
export * from "./economics";
export * from "./institutions";
export * from "./health";
export * from "./education";
export * from "./fertility";
export * from "./water-and-sanitation"
export * from "./physical";
export * from "./climate";