# Generated by Django 5.2.3 on 2025-06-23 13:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CivilOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="संस्थाको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="संस्थाको नाम (नेपाली)"
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("CBO", "सामुदायिक संस्था"),
                            ("NGO", "गैरसरकारी संस्था"),
                            ("INGO", "अन्तर्राष्ट्रिय गैरसरकारी संस्था"),
                            ("COOPERATIVE", "सहकारी संस्था"),
                            ("USER_GROUP", "उपभोक्ता समूह"),
                            ("WOMEN_GROUP", "महिला समूह"),
                            ("YOUTH_CLUB", "युवा क्लब"),
                            ("FARMERS_GROUP", "कृषक समूह"),
                            ("MOTHERS_GROUP", "आमा समूह"),
                        ],
                        max_length=20,
                        verbose_name="संस्थाको प्रकार",
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="दर्ता नम्बर"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(blank=True, null=True, verbose_name="दर्ता मिति"),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(default=0, verbose_name="कुल सदस्य"),
                ),
                (
                    "male_members",
                    models.PositiveIntegerField(default=0, verbose_name="पुरुष सदस्य"),
                ),
                (
                    "female_members",
                    models.PositiveIntegerField(default=0, verbose_name="महिला सदस्य"),
                ),
                (
                    "working_areas",
                    models.TextField(blank=True, verbose_name="कार्य क्षेत्रहरू"),
                ),
                (
                    "annual_budget_npr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="वार्षिक बजेट (रुपैयाँ)",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="सम्पर्क व्यक्ति"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="सम्पर्क नम्बर"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="सक्रिय छ"),
                ),
            ],
            options={
                "verbose_name": "नागरिक संगठन",
                "verbose_name_plural": "नागरिक संगठनहरू",
            },
        ),
        migrations.CreateModel(
            name="CommunityGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="समूहको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="समूहको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS_GROUP", "बचत समूह"),
                            ("WATER_USER", "पानी उपभोक्ता समूह"),
                            ("FOREST_USER", "वन उपभोक्ता समूह"),
                            ("MOTHERS_GROUP", "आमा समूह"),
                            ("FARMERS_GROUP", "कृषक समूह"),
                            ("TOLE_COMMITTEE", "टोल समिति"),
                            ("SCHOOL_COMMITTEE", "विद्यालय समिति"),
                            ("HEALTH_COMMITTEE", "स्वास्थ्य समिति"),
                            ("MEDIATION_COMMITTEE", "मेलमिलाप समिति"),
                        ],
                        max_length=30,
                        verbose_name="समूहको प्रकार",
                    ),
                ),
                (
                    "formation_date",
                    models.DateField(blank=True, null=True, verbose_name="गठन मिति"),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(default=0, verbose_name="कुल सदस्य"),
                ),
                (
                    "male_members",
                    models.PositiveIntegerField(default=0, verbose_name="पुरुष सदस्य"),
                ),
                (
                    "female_members",
                    models.PositiveIntegerField(default=0, verbose_name="महिला सदस्य"),
                ),
                (
                    "chairperson_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="अध्यक्षको नाम"
                    ),
                ),
                (
                    "secretary_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="सचिवको नाम"
                    ),
                ),
                (
                    "main_activities",
                    models.TextField(blank=True, verbose_name="मुख्य गतिविधिहरू"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="सक्रिय छ"),
                ),
            ],
            options={
                "verbose_name": "सामुदायिक समूह",
                "verbose_name_plural": "सामुदायिक समूहहरू",
            },
        ),
        migrations.CreateModel(
            name="DepartmentalStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "department_name",
                    models.CharField(max_length=100, verbose_name="विभागको नाम"),
                ),
                (
                    "department_name_nepali",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="विभागको नाम (नेपाली)"
                    ),
                ),
                (
                    "head_position",
                    models.CharField(max_length=100, verbose_name="प्रमुखको पद"),
                ),
                (
                    "total_employees",
                    models.PositiveIntegerField(default=0, verbose_name="कुल कर्मचारी"),
                ),
                (
                    "permanent_employees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="स्थायी कर्मचारी"
                    ),
                ),
                (
                    "temporary_employees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="अस्थायी कर्मचारी"
                    ),
                ),
                (
                    "contract_employees",
                    models.PositiveIntegerField(default=0, verbose_name="करार कर्मचारी"),
                ),
                (
                    "main_functions",
                    models.TextField(blank=True, verbose_name="मुख्य कार्यहरू"),
                ),
                (
                    "established_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="स्थापना वर्ष"
                    ),
                ),
            ],
            options={
                "verbose_name": "विभागीय संरचना",
                "verbose_name_plural": "विभागीय संरचनाहरू",
            },
        ),
        migrations.CreateModel(
            name="ElectedRepresentative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="नाम (नेपाली)"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("MAYOR", "मेयर/अध्यक्ष"),
                            ("DEPUTY_MAYOR", "उपमेयर/उपाध्यक्ष"),
                            ("WARD_CHAIRPERSON", "वडा अध्यक्ष"),
                            ("WARD_MEMBER", "वडा सदस्य"),
                            ("DALIT_WOMAN_MEMBER", "दलित महिला सदस्य"),
                            ("WOMAN_MEMBER", "महिला सदस्य"),
                        ],
                        max_length=30,
                        verbose_name="पद",
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "political_party",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="राजनीतिक दल"
                    ),
                ),
                (
                    "election_year",
                    models.PositiveIntegerField(verbose_name="निर्वाचन वर्ष"),
                ),
                ("term_start_date", models.DateField(verbose_name="कार्यकाल सुरु मिति")),
                ("term_end_date", models.DateField(verbose_name="कार्यकाल अन्त्य मिति")),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="शिक्षा स्तर"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="सम्पर्क नम्बर"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="इमेल"),
                ),
            ],
            options={
                "verbose_name": "निर्वाचित प्रतिनिधि",
                "verbose_name_plural": "निर्वाचित प्रतिनिधिहरू",
            },
        ),
        migrations.CreateModel(
            name="MunicipalAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "asset_name",
                    models.CharField(max_length=200, verbose_name="सम्पत्तिको नाम"),
                ),
                (
                    "asset_name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="सम्पत्तिको नाम (नेपाली)"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("LAND", "जग्गा"),
                            ("BUILDING", "भवन"),
                            ("VEHICLE", "सवारी साधन"),
                            ("EQUIPMENT", "उपकरण"),
                            ("MACHINERY", "मेसिन"),
                            ("FURNITURE", "फर्निचर"),
                            ("INFRASTRUCTURE", "पूर्वाधार"),
                        ],
                        max_length=30,
                        verbose_name="सम्पत्तिको प्रकार",
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(blank=True, null=True, verbose_name="प्राप्ति मिति"),
                ),
                (
                    "acquisition_value_npr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="प्राप्ति मूल्य (रुपैयाँ)",
                    ),
                ),
                (
                    "current_value_npr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="हालको मूल्य (रुपैयाँ)",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                            ("DAMAGED", "बिग्रिएको"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="अवस्था",
                    ),
                ),
                (
                    "is_functional",
                    models.BooleanField(default=True, verbose_name="काम गर्ने अवस्थामा छ"),
                ),
            ],
            options={
                "verbose_name": "नगरपालिका सम्पत्ति",
                "verbose_name_plural": "नगरपालिका सम्पत्तिहरू",
            },
        ),
        migrations.CreateModel(
            name="MunicipalityEmployee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="नाम (नेपाली)"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="कर्मचारी नं."
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="पद")),
                ("department", models.CharField(max_length=100, verbose_name="विभाग")),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "स्थायी"),
                            ("TEMPORARY", "अस्थायी"),
                            ("CONTRACT", "करार"),
                            ("VOLUNTEER", "स्वयंसेवक"),
                        ],
                        max_length=20,
                        verbose_name="कर्मचारी प्रकार",
                    ),
                ),
                (
                    "service_level",
                    models.CharField(blank=True, max_length=50, verbose_name="सेवा स्तर"),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="शिक्षा स्तर"
                    ),
                ),
                ("joining_date", models.DateField(verbose_name="भर्ना मिति")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="सक्रिय छ"),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="सम्पर्क नम्बर"
                    ),
                ),
            ],
            options={
                "verbose_name": "नगरपालिका कर्मचारी",
                "verbose_name_plural": "नगरपालिका कर्मचारीहरू",
            },
        ),
        migrations.CreateModel(
            name="PolicyRegulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="शीर्षक")),
                (
                    "title_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="शीर्षक (नेपाली)"
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("ACT", "ऐन"),
                            ("POLICY", "नीति"),
                            ("REGULATION", "नियम"),
                            ("GUIDELINE", "निर्देशिका"),
                            ("STANDARD", "मापदण्ड"),
                            ("PROCEDURE", "कार्यविधि"),
                        ],
                        max_length=20,
                        verbose_name="प्रकार",
                    ),
                ),
                ("approval_date", models.DateField(verbose_name="स्वीकृति मिति")),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="लागु मिति"),
                ),
                (
                    "approval_authority",
                    models.CharField(max_length=100, verbose_name="स्वीकृति निकाय"),
                ),
                ("objectives", models.TextField(blank=True, verbose_name="उद्देश्यहरू")),
                (
                    "key_provisions",
                    models.TextField(blank=True, verbose_name="मुख्य व्यवस्थाहरू"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="लागु छ")),
                (
                    "amendment_count",
                    models.PositiveIntegerField(default=0, verbose_name="संशोधन संख्या"),
                ),
                (
                    "last_amendment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="अन्तिम संशोधन मिति"
                    ),
                ),
            ],
            options={
                "verbose_name": "नीति नियम",
                "verbose_name_plural": "नीति नियमहरू",
            },
        ),
        migrations.CreateModel(
            name="ProjectProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="आयोजनाको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="आयोजनाको नाम (नेपाली)"
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("INFRASTRUCTURE", "पूर्वाधार"),
                            ("SOCIAL", "सामाजिक"),
                            ("ECONOMIC", "आर्थिक"),
                            ("ENVIRONMENT", "वातावरणीय"),
                            ("GOVERNANCE", "सुशासन"),
                            ("DISASTER_RISK_REDUCTION", "विपद् जोखिम न्यूनीकरण"),
                            ("CAPACITY_BUILDING", "क्षमता विकास"),
                        ],
                        max_length=30,
                        verbose_name="आयोजनाको प्रकार",
                    ),
                ),
                (
                    "implementing_ward",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="कार्यान्वयन वडा"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="सुरु मिति")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="समाप्ति मिति"),
                ),
                (
                    "total_budget_npr",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="कुल बजेट (रुपैयाँ)"
                    ),
                ),
                (
                    "expenditure_npr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="खर्च (रुपैयाँ)",
                    ),
                ),
                (
                    "funding_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="बजेटको स्रोत"
                    ),
                ),
                (
                    "implementing_agency",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="कार्यान्वयन निकाय"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "योजना"),
                            ("ONGOING", "जारी"),
                            ("COMPLETED", "सम्पन्न"),
                            ("SUSPENDED", "रोकिएको"),
                            ("CANCELLED", "रद्द"),
                        ],
                        default="PLANNING",
                        max_length=20,
                        verbose_name="स्थिति",
                    ),
                ),
                (
                    "beneficiaries",
                    models.PositiveIntegerField(
                        default=0, verbose_name="लाभान्वित जनसंख्या"
                    ),
                ),
                ("objectives", models.TextField(blank=True, verbose_name="उद्देश्यहरू")),
                ("achievements", models.TextField(blank=True, verbose_name="उपलब्धिहरू")),
            ],
            options={
                "verbose_name": "आयोजना कार्यक्रम",
                "verbose_name_plural": "आयोजना कार्यक्रमहरू",
            },
        ),
        migrations.CreateModel(
            name="AnnualBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "fiscal_year",
                    models.CharField(max_length=10, verbose_name="आर्थिक वर्ष"),
                ),
                (
                    "total_budget_npr",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="कुल बजेट (रुपैयाँ)"
                    ),
                ),
                (
                    "internal_revenue_npr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="आन्तरिक आय (रुपैयाँ)",
                    ),
                ),
                (
                    "federal_grant_npr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="संघीय अनुदान (रुपैयाँ)",
                    ),
                ),
                (
                    "provincial_grant_npr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="प्रदेश अनुदान (रुपैयाँ)",
                    ),
                ),
                (
                    "capital_expenditure_npr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="पूँजीगत खर्च (रुपैयाँ)",
                    ),
                ),
                (
                    "current_expenditure_npr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="चालु खर्च (रुपैयाँ)",
                    ),
                ),
                (
                    "development_expenditure_npr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="विकास खर्च (रुपैयाँ)",
                    ),
                ),
                (
                    "budget_utilization_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="बजेट उपयोग प्रतिशत",
                    ),
                ),
            ],
            options={
                "verbose_name": "वार्षिक बजेट",
                "verbose_name_plural": "वार्षिक बजेटहरू",
                "unique_together": {("fiscal_year",)},
            },
        ),
        migrations.CreateModel(
            name="ServiceDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "service_name",
                    models.CharField(max_length=100, verbose_name="सेवाको नाम"),
                ),
                (
                    "service_name_nepali",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="सेवाको नाम (नेपाली)"
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("BIRTH_REGISTRATION", "जन्म दर्ता"),
                            ("DEATH_REGISTRATION", "मृत्यु दर्ता"),
                            ("MARRIAGE_REGISTRATION", "विवाह दर्ता"),
                            ("CITIZENSHIP", "नागरिकता"),
                            ("RECOMMENDATION", "सिफारिस"),
                            ("BUSINESS_REGISTRATION", "व्यवसाय दर्ता"),
                            ("LAND_REVENUE", "मालपोत"),
                            ("TAX_COLLECTION", "कर संकलन"),
                            ("BUILDING_PERMIT", "भवन निर्माण अनुमति"),
                            ("SOCIAL_SECURITY", "सामाजिक सुरक्षा"),
                        ],
                        max_length=30,
                        verbose_name="सेवाको प्रकार",
                    ),
                ),
                (
                    "service_fee_npr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="सेवा शुल्क (रुपैयाँ)",
                    ),
                ),
                (
                    "processing_time_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="प्रक्रिया समय (दिन)"
                    ),
                ),
                (
                    "required_documents",
                    models.TextField(blank=True, verbose_name="आवश्यक कागजातहरू"),
                ),
                (
                    "service_procedure",
                    models.TextField(blank=True, verbose_name="सेवा प्रक्रिया"),
                ),
                (
                    "is_online_available",
                    models.BooleanField(default=False, verbose_name="अनलाइन उपलब्ध छ"),
                ),
                (
                    "monthly_service_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="मासिक सेवा संख्या"
                    ),
                ),
                (
                    "responsible_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governance.departmentalstructure",
                        verbose_name="जिम्मेवार विभाग",
                    ),
                ),
            ],
            options={
                "verbose_name": "सेवा प्रवाह",
                "verbose_name_plural": "सेवा प्रवाहहरू",
            },
        ),
        migrations.CreateModel(
            name="ServiceFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("feedback_date", models.DateField(verbose_name="प्रतिक्रिया मिति")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="मूल्याङ्कन (१-५)",
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(blank=True, verbose_name="प्रतिक्रिया"),
                ),
                (
                    "citizen_ward",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="नागरिकको वडा",
                    ),
                ),
                (
                    "is_complaint",
                    models.BooleanField(default=False, verbose_name="गुनासो हो"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="समाधान भयो"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governance.servicedelivery",
                        verbose_name="सेवा",
                    ),
                ),
            ],
            options={
                "verbose_name": "सेवा प्रतिक्रिया",
                "verbose_name_plural": "सेवा प्रतिक्रियाहरू",
            },
        ),
    ]
